### ISSUE TITLE
import librosa error ?

### ISSUE THREAD

**Issue by ucasiggcas** [librosa/librosa#1013]
hi,
On linux after 
`pip3 install librosa`
I import the librosa ups the bug

```
Python 3.5.2

>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/__init__.py", line 123, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py", line 1825, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/usr/local/lib/python3.5/dist-packages/numba/decorators.py", line 179, in wrapper
    disp.enable_caching()
  File "/usr/local/lib/python3.5/dist-packages/numba/dispatcher.py", line 571, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/local/lib/python3.5/dist-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/local/lib/python3.5/dist-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py'
```

how to solve it ?
thx

**Comment by bmcfee** [comment]
Please fill out the issue template completely, including versions and dependencies, so that we can properly diagnose the issue.

**Comment by ucasiggcas** [comment]
Now you will see the details:
```
sudo pip3 install librosa -U
Collecting librosa
  Downloading http://pip....com/packages/0b/71/c21ccef81276d8.aaf8a91f912e65eff0fd0d74a5a19c/librosa-0.7.1.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 67.1MB/s 
Requirement already satisfied, skipping upgrade: audioread>=2.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (2.1.8)
Requirement already satisfied, skipping upgrade: numpy>=1.15.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (1.16.4)
Requirement already satisfied, skipping upgrade: scipy>=1.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (1.1.0)
Requirement already satisfied, skipping upgrade: scikit-learn!=0.19.0,>=0.14.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (0.19.2)
Requirement already satisfied, skipping upgrade: joblib>=0.12 in /usr/local/lib/python3.5/dist-packages (from librosa) (0.13.2)
Requirement already satisfied, skipping upgrade: decorator>=3.0.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (4.3.0)
Requirement already satisfied, skipping upgrade: six>=1.3 in /usr/local/lib/python3.5/dist-packages (from librosa) (1.11.0)
Requirement already satisfied, skipping upgrade: resampy>=0.2.2 in /usr/local/lib/python3.5/dist-packages (from librosa) (0.2.2)
Requirement already satisfied, skipping upgrade: numba>=0.43.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (0.44.1)
Requirement already satisfied, skipping upgrade: soundfile>=0.9.0 in /usr/local/lib/python3.5/dist-packages (from librosa) (0.10.2)
Requirement already satisfied, skipping upgrade: llvmlite>=0.29.0 in /usr/local/lib/python3.5/dist-packages (from numba>=0.43.0->librosa) (0.29.0)
Requirement already satisfied, skipping upgrade: cffi>=1.0 in /usr/local/lib/python3.5/dist-packages (from soundfile>=0.9.0->librosa) (1.11.5)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.0->soundfile>=0.9.0->librosa) (2.18)
Installing collected packages: librosa
  Running setup.py install for librosa ... done
Successfully installed librosa-0.7.1
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/__init__.py", line 123, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py", line 1825, in <module>
    def __shear_dense(X, factor=+1, axis=-1):
  File "/usr/local/lib/python3.5/dist-packages/numba/decorators.py", line 179, in wrapper
    disp.enable_caching()
  File "/usr/local/lib/python3.5/dist-packages/numba/dispatcher.py", line 571, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/local/lib/python3.5/dist-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/local/lib/python3.5/dist-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function '__shear_dense': no locator available for file '/usr/local/lib/python3.5/dist-packages/librosa/util/utils.py'
```

**Comment by lostanlen** [comment]
This results from a failure in the installation of numba.
Related: #711 #764 #789

The quick fix is to install librosa in a miniconda environment rather than by using pip.

**Comment by ucasiggcas** [comment]
so how to solve the problem ?

**Comment by lostanlen** [comment]
(1) install miniconda3: https://docs.conda.io/en/latest/miniconda.html
(2) create a conda environment: `conda env create -n myfirstenv` 
(3) activate environment: `source activate myfirstenv`
(4) install librosa: `conda install -c conda-forge librosa`

**Comment by lostanlen** [comment]
@ucasiggcas did this solve your problem?

**Comment by djricafort** [comment]
i've also encountered this issue. is there a way to install it by just using pip?

**Comment by thesby** [comment]
How does this problem happen? Any solution ? I meet the same problem on librosa 0.8

**Comment by whatsuppman** [comment]
> (1) install miniconda3: https://docs.conda.io/en/latest/miniconda.html
> (2) create a conda environment: `conda env create -n myfirstenv`
> (3) activate environment: `source activate myfirstenv`
> (4) install librosa: `conda install -c conda-forge librosa`

to install miniconda we have to uninstall anaconda(conda) ? and the instruction(commands) to set up these libs i cant set from the cmd i can set up from the anaconda prompt so that the commands that u mention up i have to set up these commands from the cmd or anaconda prompt ??

**Comment by m-arslan-hafeez** [comment]
Run the following command, issue will be resolved:

`sudo pip3 install librosa -u`

**Comment by m-arslan-hafeez** [comment]
Run the following command, issue will be resolved:

`sudo pip3 install librosa -u`

now restart your editor.

**Comment by milahu** [comment]
this is a bug in numba, see https://github.com/numba/numba/issues/5566
