### ISSUE TITLE
OSError: sndfile library not found

### ISSUE THREAD

**Issue by dnnagy** [librosa/librosa#1017]
#### Description
Cannot import `librosa`

#### Steps/Code to Reproduce

```bash
python -m librosa
```
#### Expected Results
```bash
Traceback (most recent call last):
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/site-packages/librosa/core/__init__.py", line 124, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/site-packages/librosa/core/audio.py", line 10, in <module>
    import soundfile as sf
  File "/home/dnagy/anaconda3/envs/pt11/lib/python3.6/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found
```

#### Versions

Linux-4.15.0-66-generic-x86_64-with-debian-buster-sid
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) [GCC 7.3.0]
NumPy 1.16.4
SciPy 1.3.1
librosa 0.7.1 is installed via pypi

#### What I've tried:
Installed Linuxbrew
Installed `libsndfile` with `brew install libsndfile`
This did not help.
Note that this is a remote machine, and I do not have sudo access.

**Comment by dnnagy** [comment]
I had to modify `LD_LIBRARY_PATH` since Linuxbrew installs libraries to `:$HOME/.linuxbrew/lib`

Just added the following to my `.bashrc` and now it works:
```bash
# Linuxbrew
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/.linuxbrew/lib"
```
