### ISSUE TITLE
RuntimeError: cannot cache function '__shear_dense'

### ISSUE THREAD

**Issue by openedev** [librosa/librosa#1099]
#### Description
Error while importing librosa though all the required dependencies are installed properly. 

#### Steps/Code to Reproduce
 $ python --version
 Python 3.8.2
 $ python3 -c "import audioread"
 $ python3 -c "import six"
 $ python3 -c "import joblib"
 $ python3 -c "import scipy"
 $ python3 -c "import numpy"
 $ python3 -c "import numba"
 $ python3 -c "import resampy"
 $ python3 -c "import sklearn"
 $ python3 -c "import soundfile"
 $ python3 -c "import librosa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/util/utils.py'

**Comment by bmcfee** [comment]
Please fill out the issue template so that we know what version of everything you have.  Without that information, it's very difficult for us to help you.

**Comment by openedev** [comment]
@bmcfee thanks for pointing out.

Here is the output of versions.

Linux-5.6.0-aarch64-with-glibc2.17
Python 3.8.2 (default, Apr 12 2020, 21:58:31) 
[GCC 8.4.0]
NumPy 1.18.2
SciPy 1.4.1
Traceback (most recent call last):
  File "p.py", line 5, in <module>
    import librosa; print("librosa", librosa.__version__)
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/util/utils.py'

**Comment by openedev** [comment]
@bmcfee any help?

**Comment by bmcfee** [comment]
@openedev Not sure what's going on here, but it looks like a broken installation.  Can you try uninstalling and reinstalling the package?  If that still goes through, it looks like it might be a numba issue, so I would suggest verifying that numba is installed and works properly.

**Comment by bmcfee** [comment]
@openedev were you able to get this resolved?

**Comment by bmcfee** [comment]
Closing this out from inactivity.  If it's still showing this behavior after reinstalling numba, feel free to reopen.

**Comment by yancheva** [comment]
@bmcfee I am experiencing the same issue - should I create a new ticket referencing this one, or do you prefer reopening this one? I believe the issue could be due to a permissioning problem related to numba not being able to write to a caching directory (it's reported by other projects that use `numba`, e.g.: https://github.com/numba/numba/issues/4032, https://github.com/ahwillia/tensortools/issues/29).

**Comment by bmcfee** [comment]
@yancheva Yeah, I think you're probably correct, see the discussion in #1156 .  If you can verify the proposed workaround, we can add some documentation and close it out.
