### ISSUE TITLE
Librosa does not work with numba==0.49.0

### ISSUE THREAD

**Issue by i2infinity** [librosa/librosa#1103]
#### Description
Librosa does not load when `numba==0.49.0` is installed

#### Steps/Code to Reproduce
Install `numba@0.49.0` and that just try running a `test.py` that only contains `import librosa`
```
(tensorflow2_p36) ubuntu@ip-xxx:/newvolume/net$ python test.py
```

#### Actual Results
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import librosa
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/numba/__init__.py", line 131, in <module>
    importlib.import_module(_old_mod)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/numba/typeconv/__init__.py", line 1, in <module>
    from .castgraph import Conversion
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/numba/typeconv/castgraph.py", line 6, in <module>
    from numba.utils import total_ordering
ImportError: cannot import name 'total_ordering'
```

#### Versions
```
Linux-4.15.0-1060-aws-x86_64-with-debian-buster-sid
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
[GCC 7.3.0]
NumPy 1.18.3
SciPy 1.4.1
numba 0.49.0
```

#### Fix
Downgrade to `numba==0.48.0` by doing `pip install numba==0.48.0` and everything works fine

**Comment by bmcfee** [comment]
I'm not sure this is a librosa problem: does numba 0.49 work at all in your environment?

**Comment by bmcfee** [comment]
Confirmed that there is no conflict between librosa and numba 0.49.  I'm pretty sure that @i2infinity has a local installation issue.  Can you try reinstalling numba (eg via conda)?


Log below:
```
In [1]: import librosa                                                                                                                                                                        

In [2]: librosa.show_versions()                                                                                                                                                               
INSTALLED VERSIONS
------------------
python: 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0]

librosa: 0.8.0-dev

audioread: 2.1.8
numpy: 1.18.1
scipy: 1.3.0
sklearn: 0.21.2
joblib: 0.13.2
decorator: 4.4.0
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.49.0

numpydoc: 0.9.2
sphinx: 2.4.4
sphinx_rtd_theme: 0.4.2
sphinxcontrib.versioning: 2.2.1
sphinx-gallery: None
pytest: 5.4.1
pytest-mpl: None
pytest-cov: None
matplotlib: 3.1.3
presets: 0.1.3

```

**Comment by i2infinity** [comment]
I don't have a way to duplicate this issue at this moment as the AWS instance on which I ran into this issue is gone now. Let me close this one out for now and get back once I re-build the instance. 

Thanks @bmcfee for verifying!
