### ISSUE TITLE
"version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference" Problem

### ISSUE THREAD

**Issue by triplet02** [librosa/librosa#1108]
#### Description

I have a problem with importing librosa.  
When I import librosa after importing torch, __version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference__ error occurs, and I can't figure out why.  
All my trial to __apt-get update__, __apt-get upgrade__, or upgrade my linux server 14.04 to 16.04 has failed because of __gnutls_handshake() failed: Handshake failed__ problem.  
  
But import librosa former than torch, nothing happens and simple test code seems to work.

Because of this problem, I can't run my speech recognition model code. :(  
Thought importing librosa first could fix this problem, I changed all my code to import librosa first and then import torch, but code still didn't work.  

Why this happens, and how can I fix it?  
  

#### Steps/Code to Reproduce
- librosa first, torch followed
>~$ python
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
>>> import torch
>>> librosa.\_\_version__
'0.7.2'
>>> torch.\_\_version__
'1.5.0+cu101'

- torch first, librosa followed
>~$ python
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/librosa/\_\_init__.py", line 12, in <module>
    from . import core
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/librosa/core/\_\_init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/librosa/util/\_\_init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/librosa/util/utils.py", line 5, in <module>
    import scipy.ndimage
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/\_\_init__.py", line 156, in <module>
    from . import fft
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/fft/\_\_init__.py", line 76, in <module>
    from ._basic import (
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/fft/_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/_lib/uarray.py", line 27, in <module>
    from ._uarray import *
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/_lib/_uarray/\_\_init__.py", line 114, in <module>
    from ._backend import *
  File "/home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/_lib/_uarray/_backend.py", line 15, in <module>
    from . import _uarray  # type: ignore
ImportError: /home/splab/anaconda3/envs/Kai.Lib/lib/python3.7/site-packages/scipy/_lib/_uarray/_uarray.cpython-37m-x86_64-linux-gnu.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

#### Versions

>~$ python
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-3.16.0-30-generic-x86_64-with-debian-jessie-sid
>>> import sys; print("Python", sys.version)
Python 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0]
>>> import numpy; print("NumPy", numpy.\_\_version__)
NumPy 1.18.1
>>> import scipy; print("SciPy", scipy.\_\_version__)
SciPy 1.4.1
>>> import librosa; print("librosa", librosa.\_\_version__)
librosa 0.7.2

**Comment by bmcfee** [comment]
This is almost certainly not a librosa problem, but some deeper conflict between scipy and torch.  I don't think there's anything we can do about it in this package.

Seems related to https://github.com/pytorch/pytorch/issues/6607

**Comment by triplet02** [comment]
Thanks for your reply!  
I'll try other ways to fix this problem, or maybe just totally reinstall my server.
