### ISSUE TITLE
 Cannot load when importing librosas 

### ISSUE THREAD

**Issue by linwanting** [librosa/librosa#1117]
Cannot load when importing librosa, conda local installation, version 0.7.2, the error code is as follows

import librosa
Traceback (most recent call last):

  File "G:\Anaconda\lib\site-packages\soundfile-0.10.3.post1-py3.7.egg\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')

OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-3-989066361697>", line 1, in <module>
    import librosa

  File "G:\Anaconda\lib\site-packages\librosa-0.7.2-py3.7.egg\librosa\__init__.py", line 12, in <module>
    from . import core

  File "G:\Anaconda\lib\site-packages\librosa-0.7.2-py3.7.egg\librosa\core\__init__.py", line 126, in <module>
    from .audio import *  # pylint: disable=wildcard-import

  File "G:\Anaconda\lib\site-packages\librosa-0.7.2-py3.7.egg\librosa\core\audio.py", line 10, in <module>
    import soundfile as sf

  File "G:\Anaconda\lib\site-packages\soundfile-0.10.3.post1-py3.7.egg\soundfile.py", line 163, in <module>
    _path, '_soundfile_data', _libname))

OSError: cannot load library 'G:\Anaconda\lib\site-packages\soundfile-0.10.3.post1-py3.7.egg\_soundfile_data\libsndfile64bit.dll': error 0x7e

**Comment by bmcfee** [comment]
This problem is coming from libsndfile, a dependency of `soundfile`, not librosa.

Did you install librosa (and its dependencies) from conda-forge or pip?  I recommend conda-forge if you're already in a conda environment, as that should settle the binary dependency issues.  You should probably uninstall `soundfile` first before proceding though.

**Comment by trenton3983** [comment]
> You should probably uninstall `soundfile` first before proceding though.

This was an ineffective resolution.

- For those using an Anaconda distribution, `SoundFile` is not available for a `conda` install.
- In my case I had already done `pip uninstall SoundFile`, which then lead to an import error that the package couldn't be found
- Then I did `pip install SoundFile`, which installed a newer version and resolved the error.
- The solution seems to be `pip install SoundFile --upgrade`
- This worked on Windows 10 with Anaconda, and `python 3.8.11`

**Comment by bmcfee** [comment]
> For those using an Anaconda distribution, SoundFile is not available for a conda install.

I did explicitly say conda-forge, not conda. It is definitely available on conda-forge.

**Comment by trenton3983** [comment]
conda-forge is just a channel of conda. `SoundFile` does not show up. However `pysoundfile` does. Are they the same?

[conda-forge / packages / pysoundfile 0.10.3.post1](https://anaconda.org/conda-forge/pysoundfile)

`conda install -c conda-forge pysoundfile`

**Comment by bmcfee** [comment]
Yes, they are the same. The package naming here is unfortunate, but out of our control.

**Comment by trenton3983** [comment]
Now I see, as you stated, it's the order of operation.

1. `pip uninstall SoundFile`
2. `conda install -c conda-forge librosa`
   - This will then properly install and use `pysoundfile` as a dependency

However, those finding this issue will likely have already installed `librosa`.

As I have just experienced, uninstalling `librosa` can lead to other issues because of file dependency removal with conda (even when using `--force`.

If `librosa` is installed already, then just update `SoundFile`: `pip install SoundFile --upgrade`
