### ISSUE TITLE
AttributeError: 'Memory' object has no attribute 'location'

### ISSUE THREAD

**Issue by KiAlexander** [librosa/librosa#1137]
**Describe the bug**
after iI upgrade python from 3.5 to 3.6, somthing wrong with librosa happaned as follows.
`
AttributeError: 'Memory' object has no attribute 'location'`

**To Reproduce**

```
~$ python
>>>import librosa
```

**Expected behavior**
 import librosa sucessfully

**Screenshots**

**Software versions***

```
>>> import platform; print(platform.platform())
Windows-10-10.0.17134-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.18.1
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.4.1
>>> import librosa; print("librosa", librosa.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\core\time_frequency.py", line 12, in <module>
    from ..util.deprecation import Deprecated
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\util\utils.py", line 208, in <module>
    def valid_audio(y, mono=True):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\_cache.py", line 53, in wrapper
    if self.memory.location is not None and self.level >= level:
AttributeError: 'Memory' object has no attribute 'location'
>>> librosa.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'librosa' is not defined
```

**Additional context**
```
~$ python
Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\util\utils.py", line 208, in <module>
    def valid_audio(y, mono=True):
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\librosa\_cache.py", line 53, in wrapper
    if self.memory.location is not None and self.level >= level:
AttributeError: 'Memory' object has no attribute 'location'
```

**Comment by bmcfee** [comment]
I'm pretty sure this problem has already been fixed, but what versions of librosa and joblib are you using?  There was a version of joblib some months back that caused issues on some python versions

**Comment by KiAlexander** [comment]
librosa verison: librosa==0.7.2
joblib version: joblib==0.14.0

how can I solve this prombelm? thx.

**Comment by bmcfee** [comment]
Are you sure that you have joblib 0.14.0 and not an earlier version?  Can you try reinstalling joblib in your conda environment?

**Comment by KiAlexander** [comment]
thanks，I uninstall joblib twice and install it again, then it works.
I find my joblib veison is 0.14.0 in first, after I uninstall joblib, the version becomes to 0.11, which I guess is called in fact each time.
