### ISSUE TITLE
Documentation build problems

### ISSUE THREAD

**Issue by jonashaag** [librosa/librosa#1153]
The documentation does not build out of the box for me.

With a fresh checkout and virtualenv setup, I get this error:

```
$ make html

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/private/tmp/librosa/docs/conf.py", line 60, in <module>
    raise RuntimeError("You need a recent enough version of matplotlib")
RuntimeError: You need a recent enough version of matplotlib
```

Turns out this actually a suppressed version of this traceback:

```
# in conf.py
>>> from matplotlib.sphinxext import plot_directive

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 152, in <module>
    import matplotlib.pyplot as plt
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2282, in <module>
    switch_backend(rcParams["backend"])
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/j/.asdf/installs/python/3.8.2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/private/tmp/librosa/docs/venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 6, in <module>
    import tkinter as tk
  File "/Users/j/.asdf/installs/python/3.8.2/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

Ok, somehow matplotlib tries to load a Tk based renderer (?!). If I manually change the matplotlib code to not use the Tk backend, now I get this error:

```
$ make html
...
generating gallery...

Configuration error:
The 'backreferences_dir' parameter must be of type str, pathlib.Path or None, found type <class 'bool'>
make: *** [html] Error 2
```

Ok, seems like I have to change this param from `False` to `None`. Now I get this error:

```
$ make html
...
generating gallery for auto_examples... [ 11%] plot_presets.py
Extension error:
Could not find internal sphinx-gallery thumbnail file:
/private/tmp/librosa/docs/auto_examples/images/thumb/sphx_glr_plot_presets_thumb.png
make: *** [html] Error 2
```

This is where I'm stuck.

Software versions: Python 3.8.2

```
$ pip freeze
alabaster==0.7.12
appdirs==1.4.4
attrs==19.3.0
audioread==2.1.8
Babel==2.8.0
black==19.10b0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
colorclass==2.2.0
cycler==0.10.0
decorator==4.4.2
docutils==0.16
idna==2.9
imagesize==1.2.0
Jinja2==2.11.2
joblib==0.15.1
kiwisolver==1.2.0
-e git+https://github.com/librosa/librosa@2c730101897bd3f52e149ac95d56820002f5e589#egg=librosa
llvmlite==0.32.1
MarkupSafe==1.1.1
matplotlib==3.2.1
numba==0.49.1
numpy==1.18.5
numpydoc==1.0.0
packaging==20.4
pathspec==0.8.0
Pillow==7.1.2
presets==0.1.3
pycparser==2.20
Pygments==2.6.1
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2020.1
regex==2020.5.14
requests==2.23.0
resampy==0.2.2
scikit-learn==0.23.1
scipy==1.4.1
six==1.15.0
snowballstemmer==2.0.0
SoundFile==0.10.3.post1
Sphinx==3.0.4
sphinx-gallery==0.7.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-versioning==2.2.1
sphinxcontrib-websupport==1.2.2
threadpoolctl==2.1.0
toml==0.10.1
typed-ast==1.4.1
urllib3==1.25.9
```

**Comment by bmcfee** [comment]
> The documentation does not build out of the box for me.

Thanks for reporting -- it's a known issue, more or less covered by #1145 -- primarily owing to the brittle relationship between sphinx-versioning, sphinx, and sphinx-gallery.

I have a local environment with pinned dependencies that I use to build the deployed documentation site.  Given that a doc build takes several hours to cover all historical releases, we can't reasonably tie this into a CI system like RTD or doctr.  That said, #1145 is set to be fixed for the next major release, which should at least free up the dependency stack so that a single-version build can run locally.

I'll leave this issue open for now.

**Comment by jonashaag** [comment]
Thanks! Could you give me a `pip freeze` list to build the docs for the latest release? I'd like to update the [Dash](https://kapeli.com/dash) docset which is still a v0.6.

**Comment by jonashaag** [comment]
Or maybe, if you want, you can even build it in your environment, see https://github.com/Kapeli/Dash-User-Contributions/commit/4d504a4a1b5036e5ca969233f57275cd0185e53b#diff-2346e2b39439d96e6aecb849552a8342R19 for instructions

**Comment by bmcfee** [comment]
I think it would be easiest to just copy the existing build out of our gh-pages branch?  That's where our doc site is served from anyway.

Here's a pip freeze of the conda environment i use for doc building in case you want to try anyway. Sorry that it's not minimal!
```
absl-py==0.7.1
alabaster==0.7.12
altair==3.1.0
amen==0.0.3
asn1crypto==0.24.0
astor==0.7.1
astroid==2.2.5
atomicwrites==1.3.0
attrs==19.1.0
audioread==2.1.6
Automat==0.7.0
autovizwidget==0.12.7
Babel==2.7.0
backcall==0.1.0
beautifulsoup4==4.7.1
bleach==3.1.0
blinker==1.4
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
Click==7.0
cmarkgfm==0.4.2
colorama==0.4.1
colorclass==2.2.0
conda==4.7.5
conda-build==3.18.5
conda-package-handling==1.3.10
conda-smithy==3.4.0
constantly==15.1.0
coverage==4.5.2
cryptography==2.7
cycler==0.10.0
Cython==0.29.11
decorator==4.4.0
deepspeech==0.3.0
defusedxml==0.6.0
Deprecated==1.2.5
docutils==0.14
entrypoints==0.3
-e git+git@github.com:joke2k/faker.git@d02af1971d3dc2eaf1234f93649e719093ed4028#egg=Faker
fastcache==1.1.0
filelock==3.0.12
Flask==1.0.2
future==0.17.1
gast==0.2.2
-e git+git@github.com:lowerquality/gentle.git@ce6873d8dfa3278e060fc74366fb54282b414ea3#egg=gentle
gitdb2==2.0.5
GitPython==2.1.11
glob2==0.7
gmpy2==2.0.8
google-pasta==0.1.7
greenlet==0.4.15
grpcio==1.16.1
h5py==2.9.0
hdijupyterutils==0.12.7
hyperlink==19.0.0
idna==2.8
imagesize==1.1.0
importlib-metadata==0.17
incremental==17.5.0
ipykernel==5.1.1
ipython==7.6.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isodate==0.6.0
isort==4.3.21
itsdangerous==1.1.0
-e git+git@github.com:marl/jams.git@255a5ee860b03cec8f889c9986e734a6393a0dbc#egg=jams
jax==0.1.19
jaxlib==0.1.7
jedi==0.13.3
jeepney==0.4
Jinja2==2.10.1
joblib==0.13.2
jsonpickle==1.0
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.0a3
jupyterlab-server==0.3.0
kapre==0.1.3.1
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
lazyweb==0.1
libarchive-c==2.8
-e git+git@github.com:librosa/librosa.git@995c9102b4bf93e102d4a8aee61ce393aef95f69#egg=librosa
lief==0.9.0
lightfm==1.15
llvmlite==0.29.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mir-eval==0.5
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
more-itertools==7.0.0
mpmath==1.1.0
msgpack==0.6.0
msrest==0.6.7
-e git+git@github.com:bmcfee/muda.git@f9db7a945bc16ef51e2d4dd8c2f0b2226ac797f7#egg=muda
nbconvert==5.5.0
nbformat==4.4.0
neovim-remote==2.1.4
networkx==2.3
nose==1.3.7
notebook==5.7.8
numba==0.44.1
numpy==1.16.4
numpydoc==0.9.1
oauthlib==3.0.1
olefile==0.46
openl3==0.1.0
opt-einsum==2.3.2
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.0
patsy==0.5.1
pescador==2.0.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
pkginfo==1.5.0.1
plotly==2.7.0
pluggy==0.12.0
pomegranate==0.11.0
presets==0.1.3
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.8.0
psutil==5.6.3
ptyprocess==0.6.0
-e git+git@github.com:bmcfee/pumpp.git@18d3d843d5e5e505888057fed20e58e545f4baaa#egg=pumpp
py==1.8.0
py-cpuinfo==4.0.0
py4j==0.10.7
pyarrow==0.11.1
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pydot==1.4.1
pyFFTW==0.11.1
pyflakes==2.1.1
PyGithub==1.43.6
Pygments==2.4.2
PyHamcrest==1.9.0
PyJWT==1.7.1
pykalman==0.9.5
pykerberos==1.2.1
pylint==2.3.1
pynvim==0.3.2
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrubberband==0.3.0
PySocks==1.7.0
PySoundFile==0.9.0.post1
pyspark==2.4.3
pytest==3.10.1
pytest-benchmark==3.2.2
pytest-cov==2.6.0
pytest-mpl==0.10
pytest-sugar==0.9.2
python-dateutil==2.8.0
python-dotenv==0.10.1
pytz==2019.1
PyYAML==5.1.1
pyzmq==18.0.0
qtconsole==4.5.1
readme-renderer==24.0
recmetrics==0.0.12
requests==2.22.0
requests-kerberos==0.12.0
requests-oauthlib==1.2.0
requests-toolbelt==0.9.1
-e git+git@github.com:bmcfee/resampy.git@ccb85575403663e17697bcde8e25765b022a9e0f#egg=resampy
ruamel-yaml==0.15.46
ruamel.yaml==0.15.96
scaper==1.0.0
scikit-learn==0.21.2
scikit-surprise==1.0.6
scipy==1.2.1
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
six==1.12.0
smmap2==2.0.5
snakeviz==1.0.0
snowballstemmer==1.9.0
sortedcontainers==2.0.5
SoundFile==0.10.2
soupsieve==1.8
sox==1.3.7
Sphinx==1.7.9
sphinx-gallery==0.4.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-versioning==2.2.1
sphinxcontrib-websupport==1.1.2
statsmodels==0.10.0
surprise==0.1
sympy==1.4
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
toolz==0.9.0
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
twine==1.13.0
Twisted==19.2.0
typed-ast==1.3.4
ujson==1.35
umap-learn==0.3.9
unotools==0.3.3
urllib3==1.24.2
vega-datasets==0.7.0
vsts==0.1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
widgetsnbextension==3.4.2
wrapt==1.11.2
xlrd==1.2.0
youtube-dl==2018.11.7
zipp==0.5.1
zope.interface==4.6.0
```

**Comment by jonashaag** [comment]
Building from gh-pages was very easy, thanks for the pointer!

**Comment by jonashaag** [comment]
> Given that a doc build takes several hours to cover all historical releases

FWIW, I think a documentation that takes, say, <30 minutes per commit to build is absolutely reasonable for CI.

**Comment by bmcfee** [comment]
> > Given that a doc build takes several hours to cover all historical releases
> 
> FWIW, I think a documentation that takes, say, <30 minutes per commit to build is absolutely reasonable for CI.

Agreed, but I wasn't exaggerating. A full doc build takes around 3-4 hours on my machine. Obviously this it because of how sphinx-versioning serializes builds, which I think is inevitable due to its dependence on git branches and tags. Maybe there's a better solution, but I haven't found one yet.

We ran a poll a few months back, and found that people really do value having historical docs, so I don't want to lose that.
