### ISSUE TITLE
the librosa 0.7.2 has error: 'ModuleNotFoundError: No module named 'numba.decorators''

### ISSUE THREAD

**Issue by ksaye** [librosa/librosa#1195]
The latest published librosa 0.7.2 still has the call to numba.decorators, which is not part of the numba package anymore.

How to test:

1. on Ubuntu 20.04 run 'pip3 install librosa'
2. run:  python3 -c 'import librosa'
 see the error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.8/dist-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/usr/local/lib/python3.8/dist-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'

https://github.com/librosa/librosa/blob/b0064fe7dbe8048b1d4148e61a568b6fe3fca91b/librosa/util/decorators.py#L9

**Comment by bmcfee** [comment]
This has been fixed in #1165 .

**Comment by ksaye** [comment]
@bmcfee, I agree that it is addressed in code, my point was that the fix has not been pushed to the production PyHosted servers for pip to pickup.

**Comment by bmcfee** [comment]
@ksaye yes, we know.  It's slated for the 0.8 release.  In the meantime, please pin your numba dependency.

And, while I do genuinely appreciate users raising issues for this kind of thing, it would really be helpful to follow the directions in the issue template and search for pre-existing issues before creating another post for an issue that's already been fixed.
