### ISSUE TITLE
"ImportError: DLL load failed" Issue regarding Librosa on python 3.7

### ISSUE THREAD

**Issue by arshdeepsingh2267** [librosa/librosa#1205]
Iam using python 3.7 on VS code Windows 10. I tried importing the prev versions of librosa but ended up having same error. Even tried installing Scipy and numpy of different versions but dint worked.

Below is the error iam getting:

`Traceback (most recent call last):
  File "d:/Python Stuff/YoMUSIC.py", line 15, in <module>
    import librosa
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\__init__.py", line 11, in <module>
    from . import core
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\__init__.py", line 109, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\librosa\core\audio.py", line 
10, in <module>
    import scipy.signal
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\__init__.py", line 291, in <module>
    from . import sigtools, windows
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\windows\__init__.py", line 41, in <module>
    from .windows import *
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\signal\windows\windows.py", line 9, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\Mandeep Singh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\linalg\blas.py", line 215, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.`

**Comment by bmcfee** [comment]
This problem is upstream from librosa: your scipy installation does not work.

As a general rule, I recommend using the anaconda python distribution to avoid platform problems like this.  See [here](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-vsc/) for how to integrate with VSC.

**Comment by arshdeepsingh2267** [comment]
> This problem is upstream from librosa: your scipy installation does not work.
> 
> As a general rule, I recommend using the anaconda python distribution to avoid platform problems like this. See [here](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-vsc/) for how to integrate with VSC.

Got your point, just wanted to know, as i am using pip right now, and have installed allot using it. So, while installing anaconda extension, do i have to remove pip or specifically pip's librosa module or they can co-exist.

**Comment by bmcfee** [comment]
>  So, while installing anaconda extension, do i have to remove pip or specifically pip's librosa module or they can co-exist.

You can use either: librosa exists as a conda-forge package (see librosa install docs).  If you want to use conda and pip simultaneously, you'll need to make sure to follow the directions on that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

**Comment by arshdeepsingh2267** [comment]
> > So, while installing anaconda extension, do i have to remove pip or specifically pip's librosa module or they can co-exist.
> 
> You can use either: librosa exists as a conda-forge package (see librosa install docs). If you want to use conda and pip simultaneously, you'll need to make sure to follow the directions on that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

I installed anaconda, and now the error is :
`(base) PS D:\Python Stuff> & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python.exe" "d:/Python Stuff/YoMUSIC.py"
Program 'python.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed`

And i dont know why this `& "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python.exe"`  is coming in the first line while running the program. I'll be great full if you can help.

**Comment by arshdeepsingh2267** [comment]
> > So, while installing anaconda extension, do i have to remove pip or specifically pip's librosa module or they can co-exist.
> 
> You can use either: librosa exists as a conda-forge package (see librosa install docs). If you want to use conda and pip simultaneously, you'll need to make sure to follow the directions on that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

I installed anaconda and this is coming out while running the code:

`Program 'python.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed`

This time error is not from the code but while running it `(base) PS D:\Python Stuff> & "C:/Users/Mandeep Singh/AppData/Local/Microsoft/WindowsApps/python.exe" "d:/Python Stuff/YoMUSIC.py"` why this & "c.....python.exe" is shown . Ill be greatfull if you can help me.

**Comment by arshdeepsingh2267** [comment]
> > So, while installing anaconda extension, do i have to remove pip or specifically pip's librosa module or they can co-exist.
> 
> You can use either: librosa exists as a conda-forge package (see librosa install docs). If you want to use conda and pip simultaneously, you'll need to make sure to follow the directions on that: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

Thanks, Everything is working fine.
