### ISSUE TITLE
time_stretch does not accept custom n_fft

### ISSUE THREAD

**Issue by jonashaag** [librosa/librosa#1244]
**Describe the bug**

```pycon
>>> librosa.effects.time_stretch(np.zeros(123), 1.0, n_fft=512)
.../librosa/core/spectrum.py:222: UserWarning: n_fft=512 is too small for input signal of length=123
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../librosa/effects.py", line 254, in time_stretch
    y_stretch = core.istft(stft_stretch, dtype=y.dtype, length=len_stretch, **kwargs)
TypeError: istft() got an unexpected keyword argument 'n_fft'
```

Is this an oversight in the handling of `n_fft` in `time_stretch`?

**Comment by lostanlen** [comment]
Good catch. Actually, i'm under the impression that time_stretch does not implement any keyword arguments besides `rate`.
Code: https://librosa.org/doc/latest/_modules/librosa/effects.html#time_stretch
Docs: https://librosa.org/doc/latest/generated/librosa.effects.time_stretch.html

It's not a bug in the sense that this option never worked, but still, i think it's embarassing that we document a feature that simply isn't there.

But also, friendly reminder to everyone that: (quoting phase vocoder docs)
```
This is a simplified implementation, intended primarily for reference and pedagogical purposes. It makes no attempt to handle transients, and is likely to produce many audible artifacts. 
```

For a higher-quality result, we recommend PyRubberband: https://pyrubberband.readthedocs.io/en/stable/
@jonashaag presumably this should get you back to speed
