### ISSUE TITLE
AttributeError: cffi library

### ISSUE THREAD

**Issue by mhdadk** [librosa/librosa#1246]
**Describe the bug**
If I try to load any audio file of any format, I get the following error:
```python
Traceback (most recent call last):

  File "C:\Users\Mahmoud Talaat\Documents\ncsu\semesters\fall2020\ece695_masters_research\src\utils\cough_length_distribution.py", line 6, in <module>
    x,sr = librosa.load(path = os.path.join(data_dir,'zapsplat_1.wav'),

  File "C:\ProgramData\Anaconda3\lib\site-packages\librosa\core\audio.py", line 146, in load
    with sf.SoundFile(path) as sf_desc:

  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)

  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 1170, in _open
    openfunction = _snd.sf_wchar_open

AttributeError: cffi library 'C:\ProgramData\Anaconda3\Library\bin\sndfile.dll' has no function, constant or global variable named 'sf_wchar_open'
```

**To Reproduce**
```python
import librosa
import os

data_dir = '../../data/cough'

x,sr = librosa.load(path = os.path.join(data_dir,'zapsplat_1.wav'),
                    sr = None)
```
**Expected behavior**
Return the samples of the audio file with its sampling rate.

**Screenshots**
Not applicable.

**Software versions**
```
Windows-10-10.0.18362-SP0
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.5
SciPy 1.5.0
librosa 0.8.0
INSTALLED VERSIONS
------------------
python: 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]

librosa: 0.8.0

audioread: 2.1.8
numpy: 1.18.5
scipy: 1.5.0
sklearn: 0.23.1
joblib: 0.16.0
decorator: 4.4.2
soundfile: 0.10.2
resampy: 0.2.2
numba: 0.50.1

numpydoc: 1.1.0
sphinx: 3.1.2
sphinx_rtd_theme: None
sphinxcontrib.versioning: None
sphinx-gallery: None
pytest: 5.4.3
pytest-mpl: None
pytest-cov: None
matplotlib: 3.2.2
presets: None
```
**Additional context**
I am using conda 4.8.5. I installed librosa using the following command in the Anaconda Prompt:
```
conda install -c conda-forge librosa
```
I have already tried uninstalling and re-installing librosa multiple times with no luck.

**Comment by mhdadk** [comment]
Just want to add that I get the same error if I use any other package that uses `PySoundFile` as a backend. For example, I get the same error if I use [`torchaudio`](https://pytorch.org/audio/):
```python
import torchaudio
import os

data_dir = '../../data/cough'

x,sr = torchaudio.load(os.path.join(data_dir,'zapsplat_1.wav'))
```
This might suggest that my `PySoundFile` installation is corrupted, but I am not sure. I recently uninstalled and re-installed `conda` completely so I am not sure why I would get this problem.

**Comment by mhdadk** [comment]
Please refer to [this](https://github.com/bastibe/SoundFile/issues/278) issue for the solution.
