### ISSUE TITLE
Someone knows how to install on Apple M1 Big Sur ?

### ISSUE THREAD

**Issue by dschiller** [librosa/librosa#1314]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

Done

**Describe the bug**

Installing librosa fails. Numpy seems to be not installable except the beta via `pip3 install numpy --compile --pre` ( 1.20.2 ). That done librosa is still not installable. Errors are:

```
Installing build dependencies ... error
ERROR: Command errored out with exit status 1:
Building wheel for numpy (PEP 517): finished with status 'error'
ERROR: Command errored out with exit status 1:

a lot of clang errors like:
clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly

ERROR: Failed building wheel for numpy
ERROR: Could not build wheels for numpy which use PEP 517 and cannot be installed directly
```

Wonder why it tries to build wheel for numpy as numpy is already installed.

```
pip3 freeze:
numpy==1.20.2

Using Python 3.9.1 with pyenv

```
**To Reproduce**

- pip3 install librosa << Fails

**Expected behavior**

librosa should be installed so that it can be used

**Screenshots**

![image](https://user-images.githubusercontent.com/3144986/117097356-b84b9880-ad6b-11eb-9b48-a4d2be203c98.png)

![image](https://user-images.githubusercontent.com/3144986/117097397-cf8a8600-ad6b-11eb-9c37-707c6e328ece.png)

![image](https://user-images.githubusercontent.com/3144986/117098928-124e5d00-ad70-11eb-84be-13e3931358f1.png)

![image](https://user-images.githubusercontent.com/3144986/117098954-26925a00-ad70-11eb-8156-a7959e92cf4a.png)

![image](https://user-images.githubusercontent.com/3144986/117114217-d88b4f80-ad8b-11eb-8999-ef7e41e4a585.png)

**Software versions***

```
>>> import platform; print(platform.platform())
macOS-11.3.1-arm64-arm-64bit
>>> import sys; print("Python", sys.version)
Python 3.9.1 (default, May  5 2021, 04:57:54) 
[Clang 12.0.5 (clang-1205.0.22.9)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.20.2
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.6.3
>>> import librosa; print("librosa", librosa.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'librosa'
>>> librosa.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'librosa' is not defined
>>> 
```

**Additional context**

```
lzm Issue
=========
lzm Issue occur when try to import librosa on Mac M1 Big Sur

Attempt to uninstall and install pyenv python 3.8.7 as lzm is standard lib
--------------------------------------------------------------------------
- Uninstall pyenv result in: Permission error
- brew doctor shows: access error on /usr/local
- to fix that: sudo chown -R $(whoami) $(brew --prefix)/*
- also disable pyenv in /Users/dirk.schiller/.zshrc: --- eval "$(pyenv init -)"
- Uninstall pyenv: brew uninstall pyenv
- Install: brew install pyenv
- enable pyenv in /Users/dirk.schiller/.zshrc: eval "$(pyenv init -)"
- restart machine
- test pyenv: pyenv versions << not working; pyenv not found
- uninstall homebrew, maybe wrong location on M1; should be in /opt/homebrew: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
- install homebrew: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
- create file /Users/dirk.schiller/.zprofile:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/dirk.schiller/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
- restart terminal
- test brew: brew
- install pyenv: brew install pyenv
- test pyenv: pyenv versions
- install python: pyenv install 3.8.7 << BUILD FAILED (OS X 11.3.1 using python-build 20180424)
    Inspect or clean up the working tree at /var/folders/s7/n_8563956cq7vj_hx_5xtqtr0000gn/T/python-build.20210505045239.4455
- remove /private/var/folders/s7/n_8563956cq7vj_hx_5xtqtr0000gn/T/python-build.20210505045239.4455
- install python: pyenv install 3.9.1
- set python version: pyenv global 3.9.1

Check librosa
-------------
- install librosa: python -m pip install librosa << fails with tons of errors

Use Conda
---------
- install miniforge: brew install miniforge
- create environment: conda create -n .venv python 
- activate environment: conda activate .venv
- install librosa: conda install scikit-learn librosa
- install python: conda create -n py39 python=3.9
- init conda: conda init zsh
- reopen terminal
- activate python 3.9: conda activate py39

numpy not m1 ready; use beta
----------------------------
- install numpy beta: pip3 install numpy --compile --pre

Check librosa
-------------
- install librosa: python -m pip install librosa << fails with tons of errors

Remove conda
------------
- uninstall conda: brew uninstall miniforge

reinstall numpy beta
--------------------
- check correct python pyenv version ( should be 3.9.1 ): pyenv versions
- install numpy beta: pip3 install numpy --compile --pre
- check numpy is installed ( should list numpy ): pip3 freeze
- check numpy:
    python
    import numpy
    exit()

Check librosa
-------------
- install librosa: pip3 install librosa  << fails with tons of errors
- install librosa beta: pip3 install ibrosa --compile --pre << seems there is no beta

- update .zproflie:
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/dirk.schiller/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"eval "$(/opt/homebrew/bin/brew shellenv)"
    eval "$(pyenv init -)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
- update .zshrc: mine is empty now; removed the pyenv setting and moved it to .zprofile

Install scipy
-------------
- install cython: pip3 install cython pybind11
- install fortran: brew install openblas gfortran
- where to find libs: export OPENBLAS=/opt/homebrew/opt/openblas/lib/
- compile and install scipy: pip3 install --no-binary :all: --no-use-pep517 scipy

Check librosa
-------------
- install librosa: pip3 install librosa << still fails; less errors but not working

Ask community
-------------
https://github.com/librosa/librosa/issues/1314

Try installing python 3.6
-------------------------
Source: https://github.com/librosa/librosa/issues/1270
- uninstall python 3.9: pyenv uninstall 3.9.1
- install python: pyenv install python 3.6.13 << BUILD FAILED
- install python: pyenv install python 3.6.7 << BUILD FAILED
- install python: pyenv install 3.8.9 << BUILD FAILED

Back to 3.9
-----------
- install python: pyenv install 3.9.4
- activate python 3.9: pyenv global 3.9.1
- install numpy: pip3 install numpy
- install scipy: pip3 install scipy
- install librosa: pip3 install librosa << failed

llvmlite issues
---------------
Source: https://github.com/numba/llvmlite/issues/693
Source: https://github.com/numba/numba/issues/6345#issuecomment-759509837
- try install numba: pip3 install numba << fails like librosa
- try install llvmlite: pip3 install llvmlite << fails like librosa and numba
```

**Comment by bmcfee** [comment]
I think the last two lines of your post indicate the problem: if numba and llvmlite won't install, then neither will librosa.  Once those are installed (as well as the other dependencies), there's no reason librosa should fail anymore.

**Comment by bmcfee** [comment]
Closing this out as an upstream issue.

**Comment by maiqingqiang** [comment]
```bash
brew install llvm@11
echo 'export PATH="/opt/homebrew/opt/llvm@11/bin:$PATH"' >> ~/.zshrc
pip install librosa
```
@dschiller
