### ISSUE TITLE
different win_length while using mel_to_audio 

### ISSUE THREAD

**Issue by ddoron9** [librosa/librosa#1344]
librosa__version__ 0.8.1  
Hi 

I'm trying to reconstruct a mel spectrogram to wav file. but if I put the same win_length, it shows error like below. how can it solved? 

`sr, n_fft, wl, hl = 44100, 1103, 1103, 441 
window = 'hamming'
S = librosa.core.stft(wav,
                n_fft=n_ffts,
                hop_length=hop_length,
                win_length=win_length,
                window=window,
                center=True)
        S = np.abs(S)

  mel = librosa.feature.melspectrogram(y=wav,sr=sr,
        S=S,n_mels=number_of_mels)  
  output = librosa.feature.inverse.mel_to_audio(mel , sr=sr, n_fft=n_fft, hop_length=hl, win_length=wl, window='hamming') 
`

`Traceback (most recent call last):
  File "audio.py", line 306, in <module>
    reconstruct = librosa.griffinlim(S_inv, hop_length=hl, win_length=wl, window='hamming')
  File "librosa/core/spectrum.py", line 2404, in griffinlim
    length=length,
  File "/librosa/core/spectrum.py", line 371, in istft
    ifft_window = util.pad_center(ifft_window, n_fft)[:, np.newaxis]
  File "/librosa/util/utils.py", line 448, in pad_center
    ("Target size ({:d}) must be " "at least input size ({:d})").format(size, n)
librosa.util.exceptions.ParameterError: Target size (1102) must be at least input size (1103)` #

**Comment by bmcfee** [comment]
>  n_fft=num_ffts,

This could be your problem: your example code sets `n_fft = ... 1103` but then calls `stft` with a different variable `num_ffts`.  Are you sure these have the same value?

If that's not the source of the problem, there may be an edge case related to the inference of fft size from the STFT, similar to what we saw in #1040 .

Before we start chasing that down though, please verify that the triggering example code is correct and self-contained.

Also, please adhere to the issue template and report version numbers.

**Comment by ddoron9** [comment]
It was the odd number problem. I solved it by using even n_fft.

**Comment by bmcfee** [comment]
Ok, good to know. We should make it work for odd lengths as well though.

**Comment by bmcfee** [comment]
Probably related issue: #1359
