### ISSUE TITLE
unable to import librosa on raspberry pi

### ISSUE THREAD

**Issue by kubek333** [librosa/librosa#1458]
I cant import librosa on my raspberry pi. 
I installed llvmlite == 0.37.0, numba == 0.54.1, and numpy == 1.20.3 with LLVM11 (python 3.9.2) It seems to have installed well, I can import numba without errors, but when I try to import librosa I get an error:

`RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/home/pi/Desktop/test.py", line 1, in <module>
    import librosa
  File "/home/pi/.local/lib/python3.9/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.9/site-packages/librosa/core/__init__.py", line 109, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/pi/.local/lib/python3.9/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/pi/.local/lib/python3.9/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/pi/.local/lib/python3.9/site-packages/librosa/util/utils.py", line 5, in <module>
    import scipy.ndimage
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/ndimage/__init__.py", line 151, in <module>
    from ._filters import *  # noqa: F401 F403
  File "/home/pi/.local/lib/python3.9/site-packages/scipy/ndimage/_filters.py", line 37, in <module>
    from . import _nd_image
ImportError: numpy.core.multiarray failed to import
 `

I tried several versions of librosa: 0.8.0, 0.6.3, 0.9.0, 0.8.1..
When I try with a newer version of numpy it pops up error with numpy incompatibility with numba

**Comment by bmcfee** [comment]
This is a scipy and numpy problem, not a librosa problem:

```
import scipy.ndimage File "/home/pi/.local/lib/python3.9/site-packages/scipy/ndimage/__init__.py", line 151, in <module> from ._filters import * # noqa: F401 F403 File "/home/pi/.local/lib/python3.9/site-packages/scipy/ndimage/_filters.py", line 37, in <module> from . import _nd_image ImportError: numpy.core.multiarray failed to import 
```
