### ISSUE TITLE
Documentation builds are failing

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1515]
**Describe the bug**

The latest merge seems to have broken our documentation builds in a way that I don't fully understand how to trace.  The CI build fails with the following message:

```python
Extension error (sphinx_gallery.docs_resolv):
Handler <function embed_code_links at 0x7f26c1af8710> for event 'build-finished' threw an exception (exception: read error at pos 12)
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/docs/bin/sphinx-multiversion", line 8, in <module>
    sys.exit(main())
  File "/usr/share/miniconda/envs/docs/lib/python3.7/site-packages/sphinx_multiversion/main.py", line 338, in main
    subprocess.check_call(cmd, cwd=current_cwd)
  File "/usr/share/miniconda/envs/docs/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('/usr/share/miniconda/envs/docs/bin/python', '-R', '-m', 'sphinx', '-D', 'smv_metadata_path=/tmp/tmpqe5u6rml/versions.json', '-D', 'smv_current_version=main', '-c', '/home/runner/work/librosa/librosa/docs', '/tmp/tmpqe5u6rml/41766a72c30562bf6aa24c3cc06a39f5b12c342e/docs', '/home/runner/work/librosa/librosa/build/html/main')' returned non-zero exit status 2.
```

Building only the current main with my local environment gets us a little closer:

```python
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.5.0
making output directory... done

[...]

Sphinx-Gallery successfully executed 11 out of 11 files subselected by:

    gallery_conf["filename_pattern"] = '/plot'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).

embedding documentation hyperlinks...

Extension error (sphinx_gallery.docs_resolv):
Handler <function embed_code_links at 0x7f5e3a50c670> for event 'build-finished' threw an exception (exception: read error at pos 12)
make: *** [Makefile:47: html] Error 2
```

Rolling my repo back to the 0.9.1 tag, everything builds fine.  I'll try to bisect this down to a specific commit that's causing trouble.

**Comment by bmcfee** [comment]
I think I've tracked this down to some strange behavior with intersphinx mappings.  After simplifying the configuration a bit, it builds cleanly on my local environment again.  I've pushed the change to main, and if all goes well, it should resolve the issue.

**Comment by bmcfee** [comment]
Confirmed: this is now fixed.  Incidentally, sphinx 5.02 works, so we can probably remove the 4.5 pin.
