### ISSUE TITLE
Entry from Librosa to Dedian

### ISSUE THREAD

**Issue by Nilsonfsilva** [librosa/librosa#1654]
hello
It is with great pleasure that I would like to inform you that Librosa is being packaged to become part of the debian project.

To adapt the Librosa project to Debian's policies, I had to make a patch disabling both the tests and the docs/examples directory.

Both have the "data" directory, which is missing from the project repository.

From what I've seen, the "data" directory is in a separate repository. https://github.com/librosa/librosa-test-data.

If you are interested in the librosa project package in its entirety, enter a license.

Thanks!

**Comment by bmcfee** [comment]
Thanks for this.  A few comments/questions:

- I'm curious why you need to make a patch rather than omitting those parts of the repository from the package manifest?

- I would also suggest that either the `docs` directory is included entirely or not at all.  If you remove the `examples` directory, the documentation will not build properly.

- The `docs/examples` directory does not include a "data" directory.  Do you mean `audio`?  Again, this is necessary for the documentation to build correctly, at least for the html build target.  If you're building manpage targets for docs, it might not be necessary (I haven't tried).

- I'm not sure I understand your last comment.  We already have a license file in the package.  Or are you asking me to add a license file to the test-data repository?  I don't think it's necessary to include in a deb package (the resulting archive would be huge!), but you're right that that repo probably should have a license file in it.

**Comment by Nilsonfsilva** [comment]
Hi Brian McFee!
First of all, all my effort in packaging librosa is because I think that a project like yours deserves to be in our repositories.

I will try to answer your questions:
> 'm not sure I understand your last comment. We already have a license file in the package. Or are you asking me to add > a license file to the test-data repository? I don't think it's necessary to include in a deb package (the resulting archive  
> would be huge!), but you're right that that repo probably should have a license file in it.
The librosa is under license, the repository "data" is not.

Per Debian's packaging policy, we can only package any file in a repository that is under license.
If the "data" directory were inside the librosa repository, there would be no problem. Two possible solutions: either the "data" directory is copied into librosa, or a license can be added to the repository "data".

> The docs/examples directory does not include a "data" directory. Do you mean audio? 
sorry for the mistake. Yes I meant "audio

> Again, this is necessary for the documentation to build correctly, at least for the html build targe.
yes the goal is to create html pages.
the issue of documentation it is also showing errors. I think it has to do with the new updates to the "numpy" library. We had some issues with some packages that numpy relies on.
I don't know if this is the case with librosa.
follow the logs:

########################################################################
Sphinx-Gallery successfully executed 5 out of 11 files subselected by:

    gallery_conf["filename_pattern"] = '/plot'
    gallery_conf["ignore_pattern"]   = '__init__\\.py'

after excluding 0 files that had previously been run (based on MD5).


Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_audio_playback.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_audio_playback.py", line 70, in <module>
    f0, voiced_flag, voiced_probs = librosa.pyin(y,
                                    ^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/core/pitch.py", line 837, in pyin
    states = sequence.viterbi(observation_probs, transition, p_init=p_init)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py", line 1070, in viterbi
    states, logp = __viterbi(log_prob)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2329, in __call__
    return self._vectorize_call(func=func, args=vargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2403, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 2443, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py", line 1058, in _helper
    _state, logp = _viterbi(lp.T, log_trans, log_p_init)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/lib/python3/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/typed_passes.py", line 394, in run_pass
    lower.lower()
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 168, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 222, in lower_normal_function
    entry_block_tail = self.lower_function_body()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 252, in lower_function_body
    self.lower_block(block)
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 264, in lower_block
    with new_error_context('lowering "{inst}" at {loc}', inst=inst,
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/numba/core/errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
AST node line range (911, 1) is not valid

File "../../librosa/sequence.py", line 911:
def _viterbi(log_prob, log_trans, log_p_init):  # pragma: no cover
    <source elided>
    # factor in initial state distribution
    value[0] = log_prob[0] + log_p_init
    ^

During: lowering "$binop_+240.34 = arrayexpr(expr=(<built-in function add>, [Var($228binary_subscr.32, sequence.py:911), Var(log_p_init, sequence.py:882)]), ty=array(float64, 1d, C))" at /pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py (911)


/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_music_sync.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_music_sync.py", line 76, in <module>
    D, wp = librosa.sequence.dtw(X=x_1_chroma, Y=x_2_chroma, metric='cosine')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py", line 325, in dtw
    wp = __dtw_backtracking(steps, step_sizes_sigma, subseq)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(array(int32, 2d, A), Tuple(int64, OptionalType(int64)))
 
There are 22 candidate implementations:
   - Of which 20 did not match due to:
   Overload of function 'getitem': File: <numerous>: Line N/A.
     With argument(s): '(array(int32, 2d, A), Tuple(int64, OptionalType(int64)))':
    No match.
   - Of which 2 did not match due to:
   Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 166.
     With argument(s): '(array(int32, 2d, A), Tuple(int64, OptionalType(int64)))':
    Rejected as the implementation raised a specific error:
      NumbaTypeError: unsupported array index type OptionalType(int64) in Tuple(int64, OptionalType(int64))
  raised from /usr/lib/python3/dist-packages/numba/core/typing/arraydecl.py:72

During: typing of intrinsic-call at /pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py (466)

File "../../librosa/sequence.py", line 466:
def __dtw_backtracking(steps, step_sizes_sigma, subseq, start=None):  # pragma: no cover
    <source elided>
    while (subseq and cur_idx[0] > 0) or (not subseq and cur_idx != (0, 0)):
        cur_step_idx = steps[(cur_idx[0], cur_idx[1])]
        ^



/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_chroma.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_chroma.py", line 87, in <module>
    librosa.decompose.nn_filter(chroma_harm,
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/decompose.py", line 513, in nn_filter
    rec = segment.recurrence_matrix(S, axis=axis, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/segment.py", line 523, in recurrence_matrix
    rec = rec.astype(np.bool)
                     ^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'


/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_vocal_separation.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_vocal_separation.py", line 67, in <module>
    S_filter = librosa.decompose.nn_filter(S_full,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/decompose.py", line 513, in nn_filter
    rec = segment.recurrence_matrix(S, axis=axis, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/segment.py", line 523, in recurrence_matrix
    rec = rec.astype(np.bool)
                     ^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'bool'


/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_viterbi.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_viterbi.py", line 125, in <module>
    states = librosa.sequence.viterbi_discriminative(full_p, transition)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py", line 1273, in viterbi_discriminative
    states, logp = _helper(log_prob)
                   ^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py", line 1268, in _helper
    _state, logp = _viterbi(lp.T, log_trans, log_p_init)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/lib/python3/dist-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/typed_passes.py", line 394, in run_pass
    lower.lower()
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 168, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 222, in lower_normal_function
    entry_block_tail = self.lower_function_body()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 252, in lower_function_body
    self.lower_block(block)
  File "/usr/lib/python3/dist-packages/numba/core/lowering.py", line 264, in lower_block
    with new_error_context('lowering "{inst}" at {loc}', inst=inst,
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3/dist-packages/numba/core/errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
AST node line range (911, 1) is not valid

File "../../librosa/sequence.py", line 911:
def _viterbi(log_prob, log_trans, log_p_init):  # pragma: no cover
    <source elided>
    # factor in initial state distribution
    value[0] = log_prob[0] + log_p_init
    ^

During: lowering "$binop_+240.34 = arrayexpr(expr=(<built-in function add>, [Var($228binary_subscr.32, sequence.py:911), Var(log_p_init, sequence.py:882)]), ty=array(float64, 1d, C))" at /pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/sequence.py (911)


/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_hprss.py failed leaving traceback:
Traceback (most recent call last):
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/docs/examples/plot_hprss.py", line 70, in <module>
    y_harmonic = librosa.istft(D_harmonic, length=len(y))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/core/spectrum.py", line 394, in istft
    dtype = util.dtype_c2r(stft_matrix.dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/pkgs/trabalhando/PACOTES-PRONTOS/pkg-librosa/librosa/librosa-teste/librosa/librosa/util/utils.py", line 2185, in dtype_c2r
    np.dtype(complex): np.dtype(np.float).type,
                                ^^^^^^^^
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'

**Comment by bmcfee** [comment]
> sorry for the mistake. Yes I meant "audio
> 
> > Again, this is necessary for the documentation to build correctly, at least for the html build targe.
> 
> yes the goal is to create html pages.

Got it.  To be clear, the `tests/data` folder is only needed for running the unit tests, and is not needed at runtime or for building the docs.  Unless there's specific debian policy on executing unit tests for packages, I don't think it's necessary to include it.

The `docs/examples/audio/` folder is necessary for building HTML docs, and there is in fact already a license (CC-BY) for the files in question there (see README.md).  Since this is already included in the repo, I don't see any problem here either.

For the doc build issues, it kind of looks like you have a very old numpy installation:

> AttributeError: module 'numpy' has no attribute 'float'

It would be most helpful if you could report the versions of the doc build dependencies here.  See: https://github.com/librosa/librosa/blob/b461b590bcd51d4dd86825e2146a159462d622e5/setup.cfg#L70-L81
as well as the main runtime dependencies:
https://github.com/librosa/librosa/blob/b461b590bcd51d4dd86825e2146a159462d622e5/setup.cfg#L45-L58

**Comment by bmcfee** [comment]
Closing this thread out in favor of the more recent / productive #1843 discussion
