### ISSUE TITLE
pyin crashes for low frequencies and narrow fmin/fmax bands

### ISSUE THREAD

**Issue by bluenote10** [librosa/librosa#1680]
**Describe the bug**

Currnelty, `pyin` cannot handle (I) low frequencies and (II) narrow bands of `fmin` / `fmax`.

**To Reproduce (issue I)**

Testing pyin for low midi keys:

```py
import librosa

def test_pyin(frequency: float):
    sr = 44100
    y = librosa.tone(frequency=frequency, length=sr, sr=sr)
    librosa.pyin(
        y,
        fmin=0.5 * frequency,
        fmax=2.0 * frequency,
        sr=sr,
    )

for midi_key in reversed(range(20)):
    frequency = librosa.midi_to_hz(midi_key)
    print(f"Testing midi key {midi_key}, frequency = {frequency}")
    test_pyin(frequency)
```

This works up to midi key 17 but then errors. Full output:

```
Testing midi key 19, frequency = 24.499714748859326
Testing midi key 18, frequency = 23.12465141947715
Testing midi key 17, frequency = 21.826764464562746
Testing midi key 16, frequency = 20.601722307054366
Traceback (most recent call last):
  File "/tmp/debug.py", line 18, in <module>
    test_pyin(frequency)
  File "/tmp/debug.py", line 7, in test_pyin
    librosa.pyin(
  File "/home/fabian/git/ZenTabs/.venv/venv_zentabs/lib/python3.8/site-packages/librosa/core/pitch.py", line 819, in pyin
    parabolic_shifts = _parabolic_interpolation(yin_frames)
  File "/home/fabian/git/ZenTabs/.venv/venv_zentabs/lib/python3.8/site-packages/librosa/core/pitch.py", line 485, in _parabolic_interpolation
    shiftsi[..., -1] = 0
IndexError: index -1 is out of bounds for axis 1 with size 0
```

**To Reproduce (issue II)**

I also noticed that pyin doesn't like to incorporate too much prior knowledge about a frequency, i.e., making the `fmin` / `fmax` range relatively narrow. In my use case I knew that I'm searching around a certain expected `f0_expected`, so I figured it is wise to help pyin by limiting the search range symmetrically around that frequency. That fails however for all midi keys:

```py
import librosa

def test_pyin(frequency: float):
    sr = 44100
    y = librosa.tone(frequency=frequency, length=sr, sr=sr)
    librosa.pyin(
        y,
        fmin=0.9 * frequency,
        fmax=(1 / 0.9) * frequency,
        sr=sr,
    )

for midi_key in range(128):
    frequency = librosa.midi_to_hz(midi_key)
    print(f"Testing midi key {midi_key}, frequency = {frequency}")
    try:
        test_pyin(frequency)
    except Exception as e:
        print(e)
```

This fails with `index -1 is out of bounds for axis 1 with size 0` for the low keys, but this time even for midi key 0 - 26.

For midi key 27 and higher it fails with `Target size (37) must be at least input size (51)`.

**Expected behavior**

Ideally these parameter ranges should not crash. If that is too tough to support, the limitation could be documented and perhaps combined with raising an explicit "bad parameter" error.

**Software versions***

```
Linux-5.15.0-60-generic-x86_64-with-glibc2.35
Python 3.8.16 (default, Dec  7 2022, 01:12:06) 
[GCC 11.3.0]
NumPy 1.21.6
SciPy 1.9.1
librosa 0.10.0
INSTALLED VERSIONS
------------------
python: 3.8.16 (default, Dec  7 2022, 01:12:06) 
[GCC 11.3.0]

librosa: 0.10.0

audioread: 3.0.0
numpy: 1.21.6
scipy: 1.9.1
sklearn: 1.2.1
joblib: 1.2.0
decorator: 5.1.1
numba: 0.56.4
soundfile: 0.12.1
pooch: v1.7.0
soxr: 0.3.3
typing_extensions: installed, no version number available
lazy_loader: installed, no version number available
msgpack: 1.0.4

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: 3.7.0
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: 7.2.1
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: 0.4.2
presets: None
packaging: 23.0
```

**Comment by bmcfee** [comment]
> Ideally these parameter ranges should not crash. If that is too tough to support, the limitation could be documented and perhaps combined with raising an explicit "bad parameter" error.

Yes, this seems reasonable.  I'll have to look into the details here, but my expectation is that the frequency you're requesting is too low for the specified frame size (default of 2048 at 22050).  Does the error go away if you increase the frame length?

Aside: this will also affect yin.

**Comment by bluenote10** [comment]
>  Does the error go away if you increase the frame length?

Yes, it helps with issue I, i.e., it allows to go lower depending on the frame size. I don't think that it affects the issue with the narrow fmin/fmax band though.

(Note that I initially made a mistake and forgot to pass in `sr` into pyin, but it basically just shifts the point where the error occur. I've updated the post to hopefully contain the right numbers now...)

**Comment by bmcfee** [comment]
Ok, thanks for confirming.

The key lines here are https://github.com/librosa/librosa/blob/c800e74f6a6ec5c27e0fa978d7355943cce04359/librosa/core/pitch.py#L809-L811


For your configuration, we have `sr=44100`, `fmax=2*20.601722307054366`, `fmin=0.5 * 20.601722307054366`, and with a default frame length of `2048` we have `win_length = 1024`.

The resulting calculations are:

```python
In [1]: import librosa

In [2]: import numpy as np

In [3]: sr = 44100

In [4]: frame_length = 2048

In [5]: win_length = 1024

In [6]: fmax = 2 * 20.601722307054366

In [7]: fmin = 0.5 * 20.601722307054366

In [8]: np.floor(sr / fmax)
Out[8]: 1070.0

In [9]: np.ceil(sr / fmin), frame_length - win_length - 1
Out[9]: (4282.0, 1023)
```
So when the max period (min frequency) is calculated, it will want no more than 1023 samples.  The min period (max frequency) needs at least 1070 samples.
These values are later used as a slice on the frame array:
https://github.com/librosa/librosa/blob/c800e74f6a6ec5c27e0fa978d7355943cce04359/librosa/core/pitch.py#L414
which results in `1070:1023+1`, which is empty.

I think the thing to do here is detect the empty slice up front and throw an exception.  Probably this should be done as a factored-out compatibility check, as both period calculations involve a branch point (`max(..., 1)` for max_period, `min(sr/fmin, frame - win - 1)` for min_period).  Raising an informative error message will ultimately depend on which branching paths are taken.

I believe this is all correct and intended behavior (inherited from yin and pyin), but the erro r reporting could be improved so I'm flagging as enhancement.

**Comment by bmcfee** [comment]
Ok, I've implemented the above checks as follows:

```python
def __check_yin_params(*, sr, fmax, fmin, frame_length, win_length):
    """Check the feasibility of yin/pyin parameters against
    the following conditions:

    1. 0 < fmin <= fmax <= sr/2
    2. frame_length - win_length - 1 > sr/fmax
    """

    if fmax >= sr/2:
        raise ParameterError(f"fmax={fmax:.3f} cannot exceed Nyquist frequency {sr/2}")
    if fmin >= fmax:
        raise ParameterError(f"fmin={fmin:.3f} cannot exceed fmax={fmax:.3f}")
    if fmin <= 0:
        raise ParameterError(f"fmin={fmin:.3f} must be strictly positive")

    if win_length >= frame_length:
        raise ParameterError(
            f"win_length={win_length} cannot exceed given frame_length={frame_length}"
        )

    if frame_length - win_length - 1 <= sr / fmax:
        fmax_feasible = sr / (frame_length - win_length - 1)
        raise ParameterError(
            f"fmax={fmax:.3f} must be at least {fmax_feasible:.3f} for frame_length={frame_length}, win_length={win_length}, and sr={sr}"
        )
```
and with the following test code (adapted from above):
```
In [4]: import librosa
   ...: 
   ...: def test_pyin(frequency: float):
   ...:     sr = 44100
   ...:     y = librosa.tone(frequency=frequency, duration=3, sr=sr)
   ...:     librosa.yin(
   ...:         y,
   ...:         fmin=0.9 * frequency,
   ...:         fmax=(1 / 0.9) * frequency,
   ...:         sr=sr,
   ...:         center=False
   ...:     )
   ...: 
   ...: for midi_key in range(128):
   ...:     frequency = librosa.midi_to_hz(midi_key)
   ...:     print(f"Testing midi key {midi_key}, frequency = {frequency}")
   ...:     try:
   ...:         test_pyin(frequency)
   ...:     except Exception as e:
   ...:         print(e)
```
get the following outputs:
```
Testing midi key 0, frequency = 8.175798915643707
fmax=9.084 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 1, frequency = 8.661957218027252
fmax=9.624 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 2, frequency = 9.177023997418988
fmax=10.197 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 3, frequency = 9.722718241315029
fmax=10.803 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 4, frequency = 10.300861153527183
fmax=11.445 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 5, frequency = 10.913382232281373
fmax=12.126 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 6, frequency = 11.562325709738575
fmax=12.847 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 7, frequency = 12.249857374429663
fmax=13.611 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 8, frequency = 12.978271799373287
fmax=14.420 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 9, frequency = 13.75
fmax=15.278 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 10, frequency = 14.567617547440307
fmax=16.186 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 11, frequency = 15.433853164253883
fmax=17.149 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 12, frequency = 16.351597831287414
fmax=18.168 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 13, frequency = 17.323914436054505
fmax=19.249 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 14, frequency = 18.354047994837977
fmax=20.393 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 15, frequency = 19.445436482630058
fmax=21.606 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 16, frequency = 20.601722307054366
fmax=22.891 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 17, frequency = 21.826764464562746
fmax=24.252 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 18, frequency = 23.12465141947715
fmax=25.694 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 19, frequency = 24.499714748859326
fmax=27.222 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 20, frequency = 25.956543598746574
fmax=28.841 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 21, frequency = 27.5
fmax=30.556 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 22, frequency = 29.13523509488062
fmax=32.372 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 23, frequency = 30.86770632850775
fmax=34.297 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 24, frequency = 32.70319566257483
fmax=36.337 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 25, frequency = 34.64782887210901
fmax=38.498 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 26, frequency = 36.70809598967594
fmax=40.787 must be at least 43.109 for frame_length=2048, win_length=1024, and sr=44100
Testing midi key 27, frequency = 38.890872965260115
Testing midi key 28, frequency = 41.20344461410875
...
[things continue working for subsequent frequencies)
```

(Testing yin, but the same check is used in pyin.)

This seems reasonable enough to me, but I'm open to suggestions if anyone wants to propose changes to the exception messages?
