### ISSUE TITLE
[Help] When I make the EXE file with librosa library, I got the error message.

### ISSUE THREAD

**Issue by YouMinJung** [librosa/librosa#1682]
Hi.

I want to make exe file with pyinstaller. I used 'librosa' library. 
When I excute the exe file i made, error message occurred. The error message is like below.

**Traceback (most recent call last):
  File "SoundProcess_Program.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "librosa\__init__.py", line 215, in <module>
  File "lazy_loader\__init__.py", line 243, in attach_stub
ValueError: Cannot load imports from non-existent stub 'C:\\Users\\AppData\\Local\\Temp\\_MEI37722\\librosa\\__init__.pyci'
[22432] Failed to execute script 'SoundProcess_Program' due to unhandled exception!**

I already used hook-extra file like below and also i set the `hidden-import=librosa`
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('librosa')
```

However, Error still occur...

What is the problem? How to fix this problem?

**Comment by ZhanhaoLiu1** [comment]
I encountered the same issue. Could you please tell me how did you fix it?

**Comment by YouMinJung** [comment]
In my case, this error occured beacaue of the lazy_loader.
Therefore, you should change `__init__.py` of librosa.

The code I changed is like below.

```
import lazy_loader as lazy
from .version import version as __version__

# In PyInstaller-frozen application, __file__ has .pyc suffix
_filename = __file__
if _filename.endswith('.pyc'):
    _filename = _filename[:-1]

__getattr__, __dir__, __all__ = lazy.attach_stub(__name__, _filename)
```
