### ISSUE TITLE
TypeError only with PyInstaller generated EXE

### ISSUE THREAD

**Issue by sean-phyx** [librosa/librosa#1690]
**Describe the bug**
I'm using pyinstaller to generate an EXE for my application. I've added a librosa-hook.py file as suggested in other issue threads and fixed a few issues that were showing up with not properly collecting the librosa files. However, after generating the EXE when run I get the error:

```
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod02_importers.py", line 151, in get_code
  File "PyInstaller\loader\pyimod01_archive.py", line 287, in extract
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "analyser.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "chroma\ChromaGenerator.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "librosa\display.py", line 90, in <module>
  File "importlib\util.py", line 247, in __getattribute__
  File "PyInstaller\loader\pyimod02_importers.py", line 335, in exec_module
  File "PyInstaller\loader\pyimod02_importers.py", line 153, in get_code
TypeError: can only concatenate str (not "dict") to str

```

**To Reproduce**
Attempt to generate an EXE with librosa imported as:
``` 
import librosa as lr
```

**Expected behavior**
A generated EXE can be run and works

**Software versions***

**Additional context**
Not sure if this is a Librosa or pyinstaller issue, or my own issue in my usage however I'd appreciate any help to fix the error.

**Comment by sean-phyx** [comment]
Yeah, so I did update lazy loader to the most recent update from the repo since I saw they merged some stuff that was creating similar errors but no luck. I did have that error before on that issue with the import not working but after fixing that I'm getting the error shown above.

**Comment by sean-phyx** [comment]
That has in fact fixed the issue! Thank you!
