### ISSUE TITLE
No module found error

### ISSUE THREAD

**Issue by ivan-marroquin** [librosa/librosa#1692]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
when I import librosa, I get this error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/util/__init__.py", line 78, in <module>
    from .files import *  # pylint: disable=wildcard-import
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/librosa/util/files.py", line 11, in <module>
    import pooch
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/pooch/__init__.py", line 19, in <module>
    from .processors import Unzip, Untar, Decompress
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/pooch/processors.py", line 14, in <module>
    import lzma
  File "/home/ivan/python_3.9.0/lib/python3.9/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**To Reproduce**
import librosa

**Expected behavior**
Being able to properly import the library

**Screenshots**

**Software versions***
I am using ubuntu 22 and I compiled python to be installed in my home directory

```
import platform; print(platform.platform()) --> Linux-5.19.0-35-generic-x86_64-with-glibc2.35

import sys; print("Python", sys.version) --> 3.9.0 (default, Sep 13 2022, 18:58:32)
                                                                    [GCC 11.2.0]

import numpy; print("NumPy", numpy.__version__) --> 1.23.3

import scipy; print("SciPy", scipy.__version__) -->  1.9.1

import librosa; print("librosa", librosa.__version__) --> 0.9.2 (from command pip list)

librosa.show_versions() --> not possible due to module not found error
```
-->

Thanks for your help,
Ivan

**Comment by bmcfee** [comment]
The error message seems clear enough: your environment does not have a working installation of lzma, which is a dependent of pooch, which librosa needs.

**Comment by ivan-marroquin** [comment]
Hi @bmcfee ,

Thanks for the suggestion. But the pooch 1.6.0 is already installed in my Python. Do you have another suggestion to try?

Ivan

**Comment by bmcfee** [comment]
> But the pooch 1.6.0 is already installed in my Python. Do you have another suggestion to try?

No - the error message above indicates that the dependencies for pooch are not installed or not working for some reason.
