### ISSUE TITLE
Inifinite process with new python (3.11.4)

### ISSUE THREAD

**Issue by tmonseigne** [librosa/librosa#1720]
Since updating to python 3.11.4 (I had 3.11.3 before). The calculation of the mfcc on the same data runs ad infinitum. I looked at it is from the first step the calculation of the melspectrogram -> stft. I did not continue to ascend the functions.
I'm on Windows 10 and test with PyCharm and VSCode (in case of)

**To Reproduce**
```python
import librosa
import numpy as np

# Générer un signal audio
duration = 5  # Durée du signal en secondes
sample_rate = 44100  # Fréquence d'échantillonnage en Hz
frequency = 440  # Fréquence fondamentale du signal en Hz
t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
waveform = 0.3 * np.sin(2 * np.pi * frequency * t)

print("Lancement de la MFCC")
# Calculer les coefficients MFCC
mfccs = librosa.feature.mfcc(y=waveform, sr=sample_rate)

# Afficher les dimensions des coefficients MFCC
print("Dimensions des MFCC :", mfccs.shape)

# Afficher les premiers coefficients MFCC
print("Premiers coefficients MFCC :", mfccs[:, :5])
```

**Software versions**
Windows-10-10.0.19045-SP0
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
NumPy 1.23.5
SciPy 1.10.1
librosa 0.10.0.post2

**Comment by bmcfee** [comment]
Thanks for this - can you please fill out the issue template with all details describing your environment?

**Comment by tmonseigne** [comment]
SOrry I haven't see this part of template it's updated

**Comment by bmcfee** [comment]
Ok, thanks for updating.  I suspect this is nothing to do with python 3.11, but rather has to do with the numba cache permission issue documented here: https://librosa.org/doc/latest/troubleshooting.html#import-librosa-hangs-indefinitely

Can you read through the above link, try the solution described there, and report back with whether it resolves the problem for you?

**Comment by tmonseigne** [comment]
I am the only user and admin on my machine.
I did not install numba directly (another lib installed it automatically since import numba does not cause an error)
So I don't have an environment variable numba
and the problem is not at the time of import but at the time of launching the function. In my example I see the first print.
If it can help here is the log when I stop the process.

```log
C:\Python311\python.exe C:\Git\BioEMA\tests\librosa_mfcc.py 
Lancement de la MFCC
Traceback (most recent call last):
  File "C:\Python311\Lib\tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Python311\\Lib\\site-packages\\librosa\\core\\__pycache__\\tmphkrva4sl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Git\BioEMA\tests\librosa_mfcc.py", line 14, in <module>
    mfccs = librosa.feature.mfcc(y=waveform, sr=sample_rate)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\lazy_loader\__init__.py", line 76, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python311\Lib\site-packages\librosa\feature\spectral.py", line 11, in <module>
    from .. import filters
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\Python311\Lib\site-packages\lazy_loader\__init__.py", line 73, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\librosa\filters.py", line 59, in <module>
    from .core.convert import note_to_hz, hz_to_midi, midi_to_hz, hz_to_octs
  File "C:\Python311\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Python311\Lib\site-packages\librosa\core\notation.py", line 799, in <module>
    @jit(nopython=True, nogil=True, cache=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\numba\core\decorators.py", line 234, in wrapper
    disp.enable_caching()
  File "C:\Python311\Lib\site-packages\numba\core\dispatcher.py", line 863, in enable_caching
    self._cache = FunctionCache(self.py_func)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\numba\core\caching.py", line 601, in __init__
    self._impl = self._impl_class(py_func)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\numba\core\caching.py", line 333, in __init__
    locator = cls.from_function(py_func, source_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\numba\core\caching.py", line 180, in from_function
    self.ensure_cache_path()
  File "C:\Python311\Lib\site-packages\numba\core\caching.py", line 107, in ensure_cache_path
    tempfile.TemporaryFile(dir=path).close()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 563, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 560, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\tempfile.py", line 262, in _mkstemp_inner
    if (_os.name == 'nt' and _os.path.isdir(dir) and
                             ^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 39, in isdir
KeyboardInterrupt

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)
```

**Comment by bmcfee** [comment]
> and the problem is not at the time of import but at the time of launching the function.

Right - like the documentation says, in 0.10 and later this shouldn't happen at import time, but *may* happen when you first call a function that in one way or another depends on numba.

I think your traceback confirms my hypothesis: you have everything installed system-wide by an administrator, but I think your code is not actually *running* as administrator.

> So I don't have an environment variable numba

Yes, you would have to create this prior to importing librosa.  The linked numba documentation should explain how to do this on windows.

**Comment by tmonseigne** [comment]
Weird this permission problem, I just updated python (with chocolatey). ANd now it's fail. I check and go back here

**Comment by bmcfee** [comment]
Great, glad it's resolved.
