### ISSUE TITLE
librosa==0.10.1 doesn`t support numpy==1.26.2

### ISSUE THREAD

**Issue by Zapzatron** [librosa/librosa#1786]
**Describe the bug**
When I try to run code with numpy==1.26.2 and librosa==0.10.1, I get an error "SystemError: initialization of _internal failed without raising an exception". But if I run code with numpy==1.23.5 and librosa==0.10.1, It is ok.

**To Reproduce**
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)

librosa.show_versions()
```

**Expected behavior**
It must don`t raise an error when I run

**Screenshots**
...

**Software versions***
```python
Windows-10-10.0.19045-SP0
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
NumPy 1.26.2
SciPy 1.10.1
librosa 0.10.1
INSTALLED VERSIONS
------------------
python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]

librosa: 0.10.1

audioread: 3.0.1
numpy: 1.26.2
scipy: 1.10.1
sklearn: 1.3.2
joblib: 1.3.2
decorator: 5.1.1
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\gpt_site\main.py", line 7, in <module>
    librosa.show_versions()
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\librosa\version.py", line 69, in show_versions
    print("{}: {}".format(dep, __get_mod_version(dep)))
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\librosa\version.py", line 17, in __get_mod_version
    mod = importlib.import_module(modname)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Python3109\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

**Additional context**
...

**Comment by bmcfee** [comment]
This appears to be a problem with your numba installation, not librosa. Maybe try reinstalling or upgrading numba?

**Comment by Zapzatron** [comment]
I upgraded numba to 0.58.1 and librosa works fine.
