### ISSUE TITLE
Librosa on Debian!

### ISSUE THREAD

**Issue by Nilsonfsilva** [librosa/librosa#1843]
Hello Librosa developers!

It is with great joy that I would like to inform you that as a Debian/Ubuntu package maintainer I am working to place Librosa in the official repositories of these two distributions.

However, I noticed that the /tests/data directory is a link that points to another repository external to the Liborsa package.

Due to the dimensions of the Librosa project, and considering that Debian periodically runs regression/reproducibility tests, aiming to maintain the integrity of the code due to the various updates that cross-dependencies and the language itself, in this case Python, undergo, and taking into account that this directory is crucial for running the tests, I come to ask:

Would there be any possibility of this directory https://github.com/librosa/librosa-test-data/tree/72bd79e448829187f6336818b3f6bdc2c2ae8f5a
be incorporated into the project?

I ask this for two reasons:
First, I cannot introduce anything external to the package, thus preserving the integrity of the code. Even if in some way, this directory is part of the project. 

And also because the repository where the files used to run the tests are not licensed.

Grateful!

**Comment by lostanlen** [comment]
Hello @Nilsonfsilva 

duplicate of #1654 ? by same OP

**Comment by Nilsonfsilva** [comment]
I even apologize for the duplication of posts.

But because I was so busy during that time, I ended up forgetting about our conversation.

I decided to resume packaging, considering the importance of this project in being an official part of our repositories.

I noticed that in the new version, you incorporated "python-soxr". I have already finished packaging it and is currently under review by Debian Developer.
Everything so that the package integrates everything you designed.

This way, I believe it is clearer why the files contained in tests/data/ are so necessary for the package. Something that may not have been done in the previous post (#654).

And I agree that unit tests are not relevant for execution. However, in Debian, testing plays a fundamental role in terms of maintaining code integrity.

As a developer, you can freeze “requirements.txt” to work with specific versions of your dependency tree and thus keep your code running smoothly.

In Debian, it doesn't work quite like that. The ecosystem concept requires maintainers to ensure that projects/packages work as smoothly as possible, even though repositories undergo changes daily.
Not an easy task. 

Robots help us with this, which are always rebuilding packages, analyzing the existence of possible failures resulting from system updates.

As it stands, Librosa needs to connect externally to test the integrity of the code. For security reasons for its servers, Debian does not allow this.

I don't know if licensing the test/data/repository would solve the problem. I would need to consult Debian Developer to see if this, in case of an exception, would be possible.

Feel free to do what works best for your project!

And I apologize if I was long-winded in my answers, but my intention is to contribute to both projects.

Dear,
Nilson F Silva!

**Comment by bmcfee** [comment]
Hi @Nilsonfsilva - thanks again for this.



> Would there be any possibility of this directory https://github.com/librosa/librosa-test-data/tree/72bd79e448829187f6336818b3f6bdc2c2ae8f5a
> be incorporated into the project?

Short answer is "no".  We removed the regression test data to a separate repository to minimize the footprint of the git archive here.  However, this repo is set up as a submodule for the main librosa repository, so as long as you clone following the directions given in the contributing guidelines, I don't believe there's any problem here:
https://github.com/librosa/librosa/blob/c295e2ada7c307bc55765b1fc72ef5c1cb7cbbac/CONTRIBUTING.md?plain=1#L16-L20
This will pull in everything needed to successfully run the tests.


> As it stands, Librosa needs to connect externally to test the integrity of the code.

It mostly does not need to connect externally for testing if you set up the git submodule properly.

There are a couple of exceptions to this, where librosa functionality is network dependent, but it has nothing to do with the test suite.  The exceptions are:
- `librosa.util.example` - uses pooch to download example audio from a hosted repository.
- `librosa.util.cite` - same, but for pulling up-to-date bibliographic information.

I see three ways to hack around this in debian tests:

1. We add pytest marks to skip testing these features when running in an isolated environment (e.g. debian).  This would be pretty easy and controllable by an environment variable, but of course, it does reduce test coverage for you.
2. You set up a mock server in your test environment to act in place of our remote data repository.  Nothing changes from the librosa test side, and coverage remains the same.  It's much more work though.
3. You pre-seed the pooch cache folder in your test environment with a pull of all example data files.  This *should* eliminate the need for any network traffic, and coverage will be unchanged.  However, we can't guarantee correctness of this strategy because it ultimately depends on how pooch handles caches, and that might change out from under us.  (I don't expect this to happen, just raising it as a possibility.)

No free lunch here, but there are options.  It might be worth looking at how similar packages that rely on external optional data (nltk, scikit-learn) handle this.



> I don't know if licensing the test/data/repository would solve the problem. I would need to consult Debian Developer to see if this, in case of an exception, would be possible.


If licensing on the submodule repository is really a problem, I think we should be able to add a license.  Note that there is no executable software in the test data repository, only data files.  Since these don't ship with the package, I'm not sure what the licensing requirements would be here from Debian's perspective.  IIRC all of the source audio for the test data came from freesound clips that are CC-licensed, though I'll need to do a little digging to pull up the specifics.  We could certainly add a CC license on the data files that we generated from the audio.

**Comment by bgermann** [comment]
Having the data files licensed under a Debian Free Software Guidelines compatible license is indeed necessary for inclusion in Debian. It is required for all files including non-executed ones.

**Comment by bgermann** [comment]
If the files are not included with the package, they are of no concern to Debian. But then they cannot be used as part of the test suite as of the no-downloads-during-build property.

**Comment by bmcfee** [comment]
> But then they cannot be used as part of the test suite as of the no-downloads-during-build property.

Ok, I think there must be something I'm fundamentally not understanding about how debian builds and tests packages then.  Please forgive my ignorance here - it's been literally decades since I've been in the weeds of .deb packages.

What exactly constitutes a "download" during the build process?  The source code must come from somewhere, and I had been assuming that this would be the primary git repository.  (Or a fork, if you want it locally managed.)  Do I have this wrong?

**Comment by bgermann** [comment]
The source comes from the source package, which holds source code that was downloaded by the packager at packaging time, not at build time. This allows to have all packages building even when servers go down. There are hundreds of old packages where Debian is the only public copy of code left.

A download during build process is constituted by opening a network connection to any machine but the building machine.

**Comment by bmcfee** [comment]
Oh right, source packages.  Too much time in python land and I forgot about those. :grin: 

Well, one option would be to include the test data in the source package but not the build.  That's not a great option, but I think it would work.

You'll still run into problems with the test that actually depend on network functionality, as I listed above.

It's sounding to me like adding an isolation mode flag to the test suite is the best option, as long as you're okay with reduced test coverage.

**Comment by Nilsonfsilva** [comment]
Thank you Bastian for the clarifications to the developers!

Bastian is a Debian developer who has been helping me get Librosa on Debian. It has already sponsored some facilities that Librosa needs.

Replying to bmcfee, yes you can reduce coverage. The important thing is that the remaining tests are sufficient to test the correct functioning of the code.

And if you decide to add the test files, see the possibility of also adding the files that the sphnix documentation requires.

**Comment by bmcfee** [comment]
> Replying to bmcfee, yes you can reduce coverage. The important thing is that the remaining tests are sufficient to test the correct functioning of crucial parts of the project.

Sounds good to me.  I'll create a new issue for the limited test mode, and start identifying what changes would need to be made.

Meanwhile, I think we actually have some overdue house cleaning in the test-data repository anyway, as some of the test data is no longer in use.

> And if you decide to add the test files, see the possibility of also adding the files that the sphnix documentation requires.

There are two types of data files that the doc build requires: those accessible through `librosa.util.example`, and those included in `docs/examples/audio`.  The latter are no problem - they are in the main repo and have a license already.

The former are going to be a problem again due to remote hosting.  This is only a problem if the docs are built in a way that executes the example code and generates result figures (eg, html or latexpdf mode).  However, if you're only generating man pages (or a different text-only format), I think this can be bypassed and there won't be any requirement of remote data.

The hitch here is that I haven't tried building manpages from our sphinx setup in a very long time, and having just tried it now, it doesn't seem compatible with some of the extensions we depend on for the doc site.  I suppose it's worth putting some cycles into figuring out what's wrong there, but it would be helpful to know what debian would require in terms of documentation format.

**Comment by Nilsonfsilva** [comment]
It's great to know that we are reaching a consensus.

Generally, sphinx documentation is formatted in most cases for HTML with Sphinx and depending on themes, among other things, other tools are used such as:
python3-sphinx-bootstrap-theme,
               python3-sphinx gallery,
               python3-sphinxcontrib.bibtex, 

But this is at your discretion. Debian has a lot in this regard.

Just be careful when choosing the libraries that will make up the documentation, to find out if it is already in Debian here:
https://tracker.debian.org/

Because otherwise we would be forced to pack our bags first. To continue packaging Librosa:

**Comment by bmcfee** [comment]
> Just be careful when choosing the libraries that will make up the documentation, to find out if it is already in Debian here:

Our documentation build requirements are fully specified in setup.cfg:
https://github.com/librosa/librosa/blob/c295e2ada7c307bc55765b1fc72ef5c1cb7cbbac/setup.cfg#L88-L101
However, this is the dependency list for building the full documentation site, which spans multiple release versions and executes all code examples, so it's probably overkill for this context.  (I.e., presets, mir_eval, ipython, etc. would not be needed.)

I think for a deb package, you would not want (or need) sphinx-multiversion, so it would have to be patched out of our conf.py.  Example code execution can otherwise be bypassed by enabling the `LIBROSA_DOC_DEBUG` environment variable; we use this during CI for quick doc build tests, but it would also work here.

**Comment by Nilsonfsilva** [comment]
All sphinx dependencies are already in Debian.

I even packed these three just for librosa:
 presets 
  sphinx-multiversion >= 0.2.3 
 mir_eval >= 0.5

If you want, you can keep them.

Nilson Silva

**Comment by bmcfee** [comment]
> If you want, you can keep them.

Cool, thanks!  I'd still advise against doing the multiversion build.  It really only makes sense for our purposes in maintaining the documentation site - for an installed package, the documentation should reflect the version that's currently installed on the system.

One of the issues that pops up with sphinx-multiversion is that our doc environment needs to simultaneously satisfy version requirements across multiple previous releases, which can involve otherwise unnecessary upper version pins.  To whatever extent that can be avoided, maintainability will be much easier for everyone involved.

**Comment by mcepl** [comment]
We have more or less working packaging in openSUSE (see [our SPEC file](https://build.opensuse.org/projects/devel:languages:python:numeric/packages/python-librosa/files/python-librosa.spec?expand=1)) and data which are usually downloaded from Internet during testing could be cached into a separate tarball. However, with 0.10.2.post1 [the script creating the cache](https://build.opensuse.org/projects/devel:languages:python:numeric/packages/python-librosa/files/librosa-create-pooch-cache.py?expand=1) fails:

```
mitmanek:python-librosa () $ python3 librosa-create-pooch-cache.py librosa-0.10.2.post1/
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.hq.ogg' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.ogg' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.txt' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.hq.ogg' from 'https://librosa.org/data/audio/198-209-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.ogg' from 'https://librosa.org/data/audio/198-209-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.txt' from 'https://librosa.org/data/audio/198-209-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.hq.ogg' from 'https://librosa.org/data/audio/3436-172162-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.ogg' from 'https://librosa.org/data/audio/3436-172162-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.txt' from 'https://librosa.org/data/audio/3436-172162-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.hq.ogg' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.ogg' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.txt' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.hq.ogg' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.ogg' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.txt' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.hq.ogg' from 'https://librosa.org/data/audio/5703-47212-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.ogg' from 'https://librosa.org/data/audio/5703-47212-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.txt' from 'https://librosa.org/data/audio/5703-47212-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).hq.ogg' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).ogg' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).txt' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Traceback (most recent call last):
  File "/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-create-pooch-cache.py", line 45, in <module>
    pc.fetch(filename)
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 561, in fetch
    self._assert_file_in_registry(fname)
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 608, in _assert_file_in_registry
    raise ValueError(f"File '{fname}' is not in the registry.")
ValueError: File 'Karissa_Hobbs_-_Let's_Go_Fishin'.hq.ogg' is not in the registry.
mitmanek:python-librosa () $ ls
_constraints             librosa-create-pooch-cache.py  librosa-pooch-cache.tar.gz                    librosa-0.10.2.post1            librosa-0.10.2.post1.tar.gz  python-librosa.changes  sysinfo.py
csr_matrix-attr-H.patch  librosa-pooch-cache            librosa-static-test-data-0.10.2.post1.tar.gz  librosa-0.10.2.post1-SPECPARTS  mark-network-tests.patch     python-librosa.spec
mitmanek:python-librosa () $ 
```

**Comment by bmcfee** [comment]
Interesting. What version of pooch do you have? There were some compatibility issues with filename escaping a while back, and that would cause exactly this program. It should be resolved by now though; can you verify that the installed version meets the minimum requirement in the librosa spec?

**Comment by mcepl** [comment]
> (using pooch 1.7.0):

**Comment by bmcfee** [comment]
Thanks @mcepl for the extra detail.  The context here is #1688 (and pr #1727), arising from https://github.com/fatiando/pooch/issues/357 .

I think this actually is a bug in our registry definition.  The files with apostrophes had been removed from the registry in #1727 and the index was updated accordingly.  However, for backward compatibility purposes, we preserved the older file paths as links and removed them from the registry going forward.

It looks like I accidentally regressed this in an otherwise unrelated PR #1829 - I'm not sure how or why this got missed in code review, but it didn't show up in the tests because the file index still omitted the bad paths.

I'm going to split this off into a separate issue to resolve in the 0.11 release.

Meanwhile, a temporary workaround would be to skip any files in registry that contain an apostrophe.  It's a silly hack, but it would circumvent the issue with minimal effort.

**Comment by mcepl** [comment]
> Meanwhile, a temporary workaround would be to skip any files in registry that contain an apostrophe. It's a silly hack, but it would circumvent the issue with minimal effort.

With this this patch:

```diff
--- librosa-create-pooch-cache.py (revision f2c9fab7ee387518f47637505f08e674)
+++ librosa-create-pooch-cache.py (working copy)
@@ -42,6 +42,7 @@
 with open(srcdir + "/" + registry_file) as fh:
     for line in fh:
         filename, hsum = line.split(" ")
-        pc.fetch(filename)
+        if "'" not in filename:
+            pc.fetch(filename)
 
 subprocess.run(["tar", "czf", f"{data_name}.tar.gz", data_name], check=True)
```

I get this error:

```
Downloading file 'version_index.msgpack' from 'https://librosa.org/data/audio/version_index.msgpack' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Traceback (most recent call last):
  File "/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-create-pooch-cache.py", line 46, in <module>
    pc.fetch(filename)
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 588, in fetch
    stream_download(
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 804, in stream_download
    hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
  File "/usr/lib/python3.11/site-packages/pooch/hashes.py", line 176, in hash_matches
    raise ValueError(
ValueError: SHA256 hash of downloaded file (version_index.msgpack) does not match the known hash: expected 9e06db4cf390d7b308a8e253f138237501b1d1a4cf46e7185f3d7081a71aef1a but got 2a7dba514f60793086d997a005a4ba8aab476e546a33183f542ef48e4f5aab80. Deleted download for safety. The downloaded file may have been corrupted or the known hash may be outdated.
```

I don’t think that workaround is as easy as you hoped it would be. Is there a way how to recalculate that index locally?

**Comment by bmcfee** [comment]
Ok, that's a separate problem, but the behavior is expected. 

We had to disable hash checks on the version index file because it can only be constructed after release. This is because dois are minted from GitHub tags (which also trigger pypi release), so there's a chicken and egg problem if we were to try to include the doi for a version upon release. Instead we push the release and then update the version file separately after the doi is created.

**Comment by bmcfee** [comment]
Following up on this, #1911 implements isolated testing so that you can bypass tests that require external resources (ie via pooch) on the command line.

This does not address the other issue of test data residing in a submodule repository, but it should simplify things otherwise.

**Comment by bmcfee** [comment]
Following up on this further: #1925 completely eliminates the test data submodule in favor of entirely self-contained tests.  I've also generated a new test recording, which will be included under some flavor of CC license.  I think this will completely resolve the blockers on debian packaging for the 1.0 release and onward.

**Comment by bmcfee** [comment]
@Nilsonfsilva I have no idea if you're interested in resuming this now, but the 1.0 release is now out and should fully resolve all blocking issues that you encountered in packaging.

**Comment by Nilsonfsilva** [comment]
Hi!
I hope you're doing well!

I'll be updating it next week!

Thanks for letting me know!



Nilson F. Silva


________________________________
De: Brian McFee ***@***.***>
Enviado: terça-feira, 11 de agosto de 2026 16:58
Para: librosa/librosa ***@***.***>
Cc: Nilsonfsilva ***@***.***>; Mention ***@***.***>
Assunto: Re: [librosa/librosa] Librosa on Debian! (Issue #1843)

[https://avatars.githubusercontent.com/u/1190540?s=20&v=4]bmcfee left a comment (librosa/librosa#1843)<https://github.com/librosa/librosa/issues/1843#issuecomment-5258157905>

@Nilsonfsilva<https://github.com/Nilsonfsilva> I have no idea if you're interested in resuming this now, but the 1.0 release is now out and should fully resolve all blocking issues that you encountered in packaging.
