### ISSUE TITLE
Issue with newly relased numpy 2.0.0

### ISSUE THREAD

**Issue by 0xdre** [librosa/librosa#1848]
***BEFORE POSTING A BUG REPORT*** Please look through [existing issues (both open and closed)](https://github.com/librosa/librosa/issues?q=is%3Aissue) to see if it's already been reported or fixed!

**Describe the bug**
Librosa pypi install is installing the latest version of numpy (2.0.0 released 06/16/24) but its being compiled with a numpy 1.x.x version leading to a numpy issue during runtime.

**To Reproduce**

import librosa

y, sr = librosa.load('./path_to_audio_file')

**Expected behavior**
Properly load an audio file as an array

**Screenshots**
![Capture](https://github.com/librosa/librosa/assets/106642932/6482c10c-55c3-4fa1-8ece-7440a69964fd)

**Software versions***

Windows-10-10.0.19045-SP0
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
NumPy 2.0.0
SciPy 1.13.1
librosa 0.10.2

INSTALLED VERSIONS
python: 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

librosa: 0.10.2

audioread: 3.0.1
numpy: 2.0.0
scipy: 1.13.1
sklearn: 1.5.0
joblib: 1.4.2
decorator: 5.1.1
numba: 0.60.0
soundfile: 0.12.1
pooch: v1.8.2

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\agine\0xdre\unisound\flutter-app\ai_exploration\exploration2.py", line 15, in <module>
    librosa.show_versions()
  File "C:\Users\agine\0xdre\unisound\flutter-app\ai_exploration\librosa\Lib\site-packages\librosa\version.py", line 69, in show_versions
    print("{}: {}".format(dep, __get_mod_version(dep)))
  File "C:\Users\agine\0xdre\unisound\flutter-app\ai_exploration\librosa\Lib\site-packages\librosa\version.py", line 17, in __get_mod_version
    mod = importlib.import_module(modname)
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\agine\0xdre\unisound\flutter-app\ai_exploration\librosa\Lib\site-packages\soxr\__init__.py", line 10, in <module>
    from . import cysoxr
soxr: None
typing_extensions: installed, no version number available
lazy_loader: 0.4
msgpack: 1.0.8

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: None
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: None
presets: None
packaging: 24.1

**Additional context**

Issue is fixed by just downgrading to numpy 1.26.4

**Comment by 0xdre** [comment]
duplicated issue
