### ISSUE TITLE
RecursionError on stft import

### ISSUE THREAD

**Issue by seatonullberg** [librosa/librosa#1857]
**Describe the bug**
Importing stft from librosa causes python to raise a RecursionError.

**To Reproduce**

Example:
```python
from librosa import stft
```
results in
```
RecursionError: maximum recursion depth exceeded
```

The start of the error looks like this before it goes recursive:

```
Traceback (most recent call last):
  File "/home/sullberg/repos/presidential-speeches/scripts/noise-reduce.py", line 1, in <module>
    from librosa import stft
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/lazy_loader/__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/librosa/core/spectrum.py", line 10, in <module>
    import scipy.signal
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/signal/__init__.py", line 320, in <module>
    from ._bsplines import *
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/signal/_bsplines.py", line 7, in <module>
    from ._signaltools import lfilter, sosfilt, lfiltic
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/signal/_signaltools.py", line 16, in <module>
    from ._ltisys import dlti
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/signal/_ltisys.py", line 29, in <module>
    from scipy.interpolate import make_interp_spline
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/interpolate/__init__.py", line 167, in <module>
    from ._interpolate import *
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/interpolate/_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/interpolate/_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/scipy/interpolate/_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/numpy/core/_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/numpy/core/_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "/home/sullberg/miniconda3/envs/presidential-speeches/lib/python3.12/site-packages/numpy/core/_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**
I would expect to not encounter a recursion error and instead import the module successfully.

**Software versions***

Please run the following Python code snippet and paste the output below.
```
import platform; print(platform.platform())
Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
import sys; print("Python", sys.version)
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:50:58) [GCC 12.3.0]
import numpy; print("NumPy", numpy.__version__)
NumPy 1.26.4
import scipy; print("SciPy", scipy.__version__)
SciPy 1.14.0
import librosa; print("librosa", librosa.__version__)
librosa 0.10.2.post1
librosa.show_versions()
RecursionError: maximum recursion depth exceeded
```

**Comment by bmcfee** [comment]
This looks to me like a problem upstream in scipy. Are you able to import and use any of the functionality listed in the traceback you posted?

**Comment by seatonullberg** [comment]
Yes, looks like it was an issue with my environment. Thanks for the response.
