### ISSUE TITLE
[Bug]: 'scipy.signal' has no attribute 'hann'

### ISSUE THREAD

**Issue by drscotthawley** [librosa/librosa#1862]
### Bug summary

Hi, the build insists on scipy>= 1.2.0, but version 1.13.1 does not support any "`scipy.signal.hann`", rather it now seems to be "[`scipy.signal.windows.hann`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.hann.html)"

 
Requirement:
```
install_requires =
    audioread >= 2.1.9
    numpy >= 1.20.3, != 1.22.0, != 1.22.1, != 1.22.2
    scipy >= 1.2.0
...
```

I have installed:
```
$ pip list | grep scipy
scipy                    1.13.1
```

### Code for reproduction

```Python
From [librosa documentation](https://librosa.org/doc/main/generated/librosa.beat.beat_track.html)


 y, sr = librosa.load(path)
 onset_env = librosa.onset.onset_strength(y=y, sr=sr)
 tempo, beats = librosa.beat.beat_track(onset_envelope=onset_env)
```
```


### Actual outcome

```
    tempo, beats = librosa.beat.beat_track(onset_envelope=onset_env)
  File "/home/shawley/envs/stomach/lib/python3.9/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/home/shawley/envs/stomach/lib/python3.9/site-packages/librosa/beat.py", line 181, in beat_track
    beats = __beat_tracker(onset_envelope, bpm, float(sr) / hop_length, tightness, trim)
  File "/home/shawley/envs/stomach/lib/python3.9/site-packages/librosa/beat.py", line 599, in __beat_tracker
    beats = __trim_beats(localscore, beats, trim)
  File "/home/shawley/envs/stomach/lib/python3.9/site-packages/librosa/beat.py", line 679, in __trim_beats
    smooth_boe = scipy.signal.convolve(localscore[beats], scipy.signal.hann(5), "same")
AttributeError: module 'scipy.signal' has no attribute 'hann'
```

### Expected outcome

That code would execute without any errors. 

### Additional information

```
$ python --version
Python 3.9.18
```

```
$ pip list | grep -E 'librosa|scipy'
librosa                  0.9.2
scipy                    1.13.1
```


# WORKAROUND: 
Downgrade `scipy` slightly: 

```
pip install 'scipy<1.13'
```
fixes it. 

### Operating system

Ubuntu

### software versions

```
$ python
Python 3.9.18 (main, Aug 25 2023, 13:20:14) 
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform()) import sys; print("Python", sys.version) import numpy; print("NumPy", numpy.version) import scipy; print("SciPy", scipy.version) import librosa; print("librosa", librosa.version)
  File "<stdin>", line 1
    import platform; print(platform.platform()) import sys; print("Python", sys.version) import numpy; print("NumPy", numpy.version) import scipy; print("SciPy", scipy.version) import librosa; print("librosa", librosa.version)
                                                ^
SyntaxError: invalid syntax
>>> librosa.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'librosa' is not defined
```
🤷 

### Installation

pip

**Comment by bmcfee** [comment]
This was fixed in pr #1766 and released in 0.10.2. if you upgrade, it should resolve itself.
