### ISSUE TITLE
[Bug]: Errors and warnings when building from source

### ISSUE THREAD

**Issue by hunterhogan** [librosa/librosa#1873]
### Bug summary

Installation of librosa fails due to a version conflict with numpy. The error indicates that numpy 2.1.1 is installed, but numba requires numpy<2.1,>=1.22.

### Code for reproduction

```Python
"""
git clone https://github.com/hunterhogan/librosa.git

C:\apps\librosa>py -m venv .

(librosa) C:\apps\librosa>python.exe -m pip install --upgrade pip

(librosa) C:\apps\librosa>python setup.py build
Traceback (most recent call last):
  File "C:\apps\librosa\setup.py", line 1, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

(librosa) C:\apps\librosa>pip list
Package Version
------- -------
pip     24.2

(librosa) C:\apps\librosa>py -V
Python 3.12.3

(librosa) C:\apps\librosa>pip install setuptools
Successfully installed setuptools-74.1.2

(librosa) C:\apps\librosa>python setup.py build

(librosa) C:\apps\librosa>python setup.py install
running install
"""
# See "Setuptools warnings" in "Actual outcome", below
# ...
# See "Setuptools error"

"""
(librosa) C:\apps\librosa>pip list
"""

# See "pip list"
```

### Setuptools warnings
```
C:\apps\librosa\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\apps\librosa\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()

```

### Setuptools error
`error: numpy 2.1.1 is installed but numpy<2.1,>=1.22 is required by {'numba'}`

### pip list
```

DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\audioread-3.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\cffi-1.17.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\decorator-5.1.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\joblib-1.4.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\lazy_loader-0.4-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\librosa-0.10.2.post1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\msgpack-1.1.0rc2-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\numba-0.60.0-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\numpy-2.1.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\pooch-1.8.2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\requests-2.32.3-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\scikit_learn-1.5.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\scipy-1.14.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\soundfile-0.12.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\apps\librosa\lib\site-packages\soxr-0.5.0.post1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Package      Version
------------ ------------
audioread    3.0.1
audioread    3.0.1
cffi         1.17.1
cffi         1.17.1
decorator    5.1.1
decorator    5.1.1
joblib       1.4.2
joblib       1.4.2
lazy_loader  0.4
lazy_loader  0.4
librosa      0.10.2.post1
librosa      0.10.2.post1
msgpack      1.1.0rc2
msgpack      1.1.0rc2
numba        0.60.0
numba        0.60.0
numpy        2.1.1
numpy        2.1.1
pip          24.2
pooch        1.8.2
pooch        1.8.2
requests     2.32.3
requests     2.32.3
scikit-learn 1.5.1
scikit-learn 1.5.1
scipy        1.14.1
scipy        1.14.1
setuptools   74.1.2
soundfile    0.12.1
soundfile    0.12.1
soxr         0.5.0.post1
soxr         0.5.0.post1


```

### Expected outcome

Installation?

### Additional information

Before today, I have always installed via `pip install librosa` or indirectly if librosa was a dependency. I don't recall ever having a problem, and I've installed dozens of times. I've only installed in `py -m venv`-flavored virtual environments. Python 3.10, 3.11, 3.12 for sure. Possibly 3.9 and/or 3.8. 

### Operating system

Microsoft Windows 11 Pro; Version 10.0.22631 Build 22631

### software versions

```sh
(librosa) C:\apps\librosa>py
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

```Python
>>> import platform; print(platform.platform()) import sys; print("Python", sys.version) import numpy; print("NumPy", numpy.version) import scipy; print("SciPy", scipy.version) import librosa; print("librosa", librosa.version)
  File "<stdin>", line 1
    import platform; print(platform.platform()) import sys; print("Python", sys.version) import numpy; print("NumPy", numpy.version) import scipy; print("SciPy", scipy.version) import librosa; print("librosa", librosa.version)
                                                ^^^^^^
SyntaxError: invalid syntax

```

```sh
(librosa) C:\apps\librosa>py
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.


```

```Python
>>> import librosa, numpy, platform, scipy, sys; print(platform.platform(), "\nPython", sys.version, "\nNumPy", numpy.version, "\nSciPy", scipy.version, "\nlibrosa", librosa.version); librosa.show_versions()
Windows-11-10.0.22631-SP0 
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)] 
NumPy <module 'numpy.version' from 'C:\\apps\\librosa\\Lib\\site-packages\\numpy-2.1.1-py3.12-win-amd64.egg\\numpy\\version.py'> 
SciPy <module 'scipy.version' from 'C:\\apps\\librosa\\Lib\\site-packages\\scipy-1.14.1-py3.12-win-amd64.egg\\scipy\\version.py'> 
librosa <module 'librosa.version' from 'C:\\apps\\librosa\\librosa\\version.py'>
INSTALLED VERSIONS
------------------
python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]

librosa: 0.10.2.post1

audioread: 3.0.1
numpy: 2.1.1
scipy: 1.14.1
sklearn: None
joblib: 1.4.2
decorator: 5.1.1
numba: None
soundfile: 0.12.1
pooch: None
soxr: 0.5.0.post1
typing_extensions: None
lazy_loader: 0.4
msgpack: 1.1.0rc2

numpydoc: None
sphinx: None
sphinx_rtd_theme: None
matplotlib: None
sphinx_multiversion: None
sphinx_gallery: None
mir_eval: None
ipython: None
sphinxcontrib.rsvgconverter: None
pytest: None
pytest_mpl: None
pytest_cov: None
samplerate: None
resampy: None
presets: None
packaging: None
```

### Installation

unable to install

**Comment by bmcfee** [comment]
> `error: numpy 2.1.1 is installed but numpy<2.1,>=1.22 is required by {'numba'}`

This error message contains everything there is to know about your issue: the version of numpy you have installed is not compatible with all dependencies.

There is an upstream issue to track this: https://github.com/numba/numba/issues/9708 but it is not something we can or should address from librosa.

As a temporary workaround, you can roll back your numpy installation to a 2.0 version.

**Comment by hunterhogan** [comment]
> This error message contains everything there is to know about your issue: the version of numpy you have installed is not compatible with all dependencies.

"My" issue? I installed using your instructions and script. The version of numpy was installed by your script. Your welcome for the detailed description of your issue.

**Comment by bmcfee** [comment]
> "My" issue?

The issue that you raised, describing a problem that you encountered.  Why are you inferring ill sentiment here?


> The version of numpy was installed by your script. Your welcome for the detailed description of your issue.

Thank you for filling out the issue template.


I do not maintain setuptools, nor do I define policy on how version constraints are interpreted throughout all python packages.  We have a set of well defined dependencies and package versions that are tested and supported.  Some of our dependencies have narrower constraints than we do; in this case, numba has an upper version pin.  At some point it will drop that upper pin, and it's not our job to keep track of that.

The problem you have identified is with numba, and has already been reported and is being worked on for the next release.  I have suggested a viable workaround until such time as that release happens.  I don't know what else you want here, or why you appear to be so angry at strangers on the internet about it.
