### ISSUE TITLE
Registry regression with bad filenames

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#1885]
We have more or less working packaging in openSUSE (see [our SPEC file](https://build.opensuse.org/projects/devel:languages:python:numeric/packages/python-librosa/files/python-librosa.spec?expand=1); I hope it is not too complicated even for non-RPM maintainer to read; of course, feel free to ask for help any time) and data which are usually downloaded from Internet during testing could be cached into a separate tarball. However, with 0.10.2.post1 [the script creating the cache](https://build.opensuse.org/projects/devel:languages:python:numeric/packages/python-librosa/files/librosa-create-pooch-cache.py?expand=1) fails (using `pooch` 1.7.0):

```
mitmanek:python-librosa () $ python3 librosa-create-pooch-cache.py librosa-0.10.2.post1/
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.hq.ogg' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.ogg' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '147793__setuniman__sweet-waltz-0i-22mi.txt' from 'https://librosa.org/data/audio/147793__setuniman__sweet-waltz-0i-22mi.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.hq.ogg' from 'https://librosa.org/data/audio/198-209-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.ogg' from 'https://librosa.org/data/audio/198-209-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '198-209-0000.txt' from 'https://librosa.org/data/audio/198-209-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.hq.ogg' from 'https://librosa.org/data/audio/3436-172162-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.ogg' from 'https://librosa.org/data/audio/3436-172162-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '3436-172162-0000.txt' from 'https://librosa.org/data/audio/3436-172162-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.hq.ogg' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.ogg' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.txt' from 'https://librosa.org/data/audio/442789__lena-orsa__happy-music-pistachio-ice-cream-ragtime.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.hq.ogg' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.ogg' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '456440__inspectorj__bird-whistling-robin-single-13.txt' from 'https://librosa.org/data/audio/456440__inspectorj__bird-whistling-robin-single-13.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.hq.ogg' from 'https://librosa.org/data/audio/5703-47212-0000.hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.ogg' from 'https://librosa.org/data/audio/5703-47212-0000.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file '5703-47212-0000.txt' from 'https://librosa.org/data/audio/5703-47212-0000.txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).hq.ogg' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).hq.ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).ogg' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).ogg' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Downloading file 'Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).txt' from 'https://librosa.org/data/audio/Hungarian_Dance_number_5_-_Allegro_in_F_sharp_minor_(string_orchestra).txt' to '/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-pooch-cache'.
Traceback (most recent call last):
  File "/home/matej/build/devel:languages:python:numeric/python-librosa/librosa-create-pooch-cache.py", line 45, in <module>
    pc.fetch(filename)
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 561, in fetch
    self._assert_file_in_registry(fname)
  File "/usr/lib/python3.11/site-packages/pooch/core.py", line 608, in _assert_file_in_registry
    raise ValueError(f"File '{fname}' is not in the registry.")
ValueError: File 'Karissa_Hobbs_-_Let's_Go_Fishin'.hq.ogg' is not in the registry.
mitmanek:python-librosa () $ ls
_constraints             librosa-create-pooch-cache.py  librosa-pooch-cache.tar.gz                    librosa-0.10.2.post1            librosa-0.10.2.post1.tar.gz  python-librosa.changes  sysinfo.py
csr_matrix-attr-H.patch  librosa-pooch-cache            librosa-static-test-data-0.10.2.post1.tar.gz  librosa-0.10.2.post1-SPECPARTS  mark-network-tests.patch     python-librosa.spec
mitmanek:python-librosa () $ 
```

_Originally posted by @mcepl in https://github.com/librosa/librosa/issues/1843#issuecomment-2477224968_

**Comment by bmcfee** [comment]
https://github.com/librosa/librosa/issues/1843#issuecomment-2479323530
