### ISSUE TITLE
librosa.util.frame returns garbage in some cases when the input is shorter than the frame length

### ISSUE THREAD

**Issue by arvidfm** [librosa/librosa#385]
```
>>> librosa.util.frame(numpy.arange(20), 40, 20).T
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.5/site-packages/librosa/util/utils.py", line 97, in frame
    ' for frame_length={:d}'.format(len(y), frame_length))
librosa.util.exceptions.ParameterError: Buffer is too short (n=20) for frame_length=40
>>> librosa.util.frame(numpy.arange(21), 40, 20).T
array([[                   0,                    1,                    2,
                           3,                    4,                    5,
                           6,                    7,                    8,
                           9,                   10,                   11,
                          12,                   13,                   14,
                          15,                   16,                   17,
                          18,                   19,                   20,
                           0,                  192,                  433,
                           1,                   16,      139966091551648,
                           4,  3385404920564867280,      139965388323448,
             139965388149232, -4963064834075467327,      139966098156432,
             139965388239112,                    0,                    0,
                           0, -7832339595949945661,      139965388323392,
             139965388149232]])
```

Using librosa 0.4.3 with numpy 1.11.1 and Python 3.5.1.

**Comment by bmcfee** [comment]
Ah, I see.  good catch!

It should raise an exception, but the length check logic isn't quite right due to a premature integer cast
```python

    # Compute the number of frames that will fit. The end may get truncated.
    n_frames = 1 + int((len(y) - frame_length) / hop_length)

    if n_frames < 1:
        raise...
```
should be:

```python
    n_frames = 1 + (len(y) - frame_length) / hop_length

    if n_frames < 1:
        raise...
    n_frames = int(n_frames)
```

**Comment by arvidfm** [comment]
I can confirm that with the changes in #386, all my data (which consists of a very large collection of sequences of all kinds of sizes) is seemingly processed correctly with util.frame.

**Comment by bmcfee** [comment]
Great, thanks @arvidfm!

Note that #386 is PR'd against the current master, which is in preparation for 0.5.  Since 0.5 won't be ready for some time, I'd recommend putting an explicit check in your code for now to keep things running with 0.4.3.
