### ISSUE TITLE
ImportError : No module named _tkinter

### ISSUE THREAD

**Issue by AliusEquinox** [librosa/librosa#423]
I don't know why it suddenly does not manage to import librosa.

I tried to create a new virtualenv dedicated to librosa but it doesn't change anything.

The error seem to be caused by tkinter and I don't care about tkinter I don't want to use any display or graphics stuff..

Can you help me with that error : (?)
```
Traceback (most recent call last):
  File "./voice_selector.py", line 7, in <module>
    import librosa
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/librosa/__init__.py", line 18, in <module>
    from . import display
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/librosa/display.py", line 21, in <module>
    import matplotlib.pyplot as plt
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from matplotlib.externals.six.moves import tkinter as Tk
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/externals/six.py", line 90, in __get__
    result = self._resolve()
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/externals/six.py", line 113, in _resolve
    return _import_module(self.mod)
  File "/home/adrien/.pyenv/versions/features-env-3.5.2/lib/python3.5/site-packages/matplotlib/externals/six.py", line 80, in _import_module
    __import__(name)
  File "/home/adrien/.pyenv/versions/3.5.2/lib/python3.5/tkinter/__init__.py", line 35, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named '_tkinter'
```

I'm working on python 3.5 and kubuntu 16.04

**Comment by bmcfee** [comment]
This looks to me like a matplotlib issue.  Can you import matplotlib directly without librosa?

**Comment by AliusEquinox** [comment]
you're rigth !
import matplotlib works good
import matplotlib.pyplot raise the same error

**Comment by bmcfee** [comment]
Ok.  I suspect your problem is lurking in non-python dependencies (tk) for the matplotlib gui interface.  Maybe check [this thread](https://stackoverflow.com/questions/36327134/matplotlib-error-no-module-named-tkinter) for pointers.

As a side note, I strongly recommend using [conda python distribution](https://anaconda.org/) over OS distributions, since the packaging handles cross-language dependencies better.

Since this is not a librosa problem, I'm going to close this out.  I hope this all helps!
