### ISSUE TITLE
Librosa no attributes

### ISSUE THREAD

**Issue by ZairMahmood** [librosa/librosa#601]
#### Description
Installed Librosa thru pip using 'pip install librosa.' It seems to import fine when running thru a script as seen in the versions part but when attempting to import it thru the IDLE, it produces another error.

#### Steps/Code to Reproduce
Ran this code that resulted in the errors shown under for versions
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import librosa; print("librosa", librosa.__version__)

removing '; print("librosa", librosa.__version__)' produces no errors

#### Error
```
>>> import librosa
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import librosa
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\librosa\core\__init__.py", line 108, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\librosa\core\time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\librosa\util\__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\ndimage\__init__.py", line 161, in <module>
    from .filters import *
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\ndimage\filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\interpolate\interpolate.py", line 21, in <module>
    import scipy.special as spec
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\special\__init__.py", line 648, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "C:\Users\zairm\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
ImportError: cannot import name '_ellipsoid'
```

#### Versions
```
Windows-10-10.0.15063-SP0
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.1
SciPy 0.19.0
Traceback (most recent call last):
  File "D:\Windows\Desktop\librosa.py", line 8, in <module>
    import librosa; print("librosa", librosa.__version__)
  File "D:\Windows\Desktop\librosa.py", line 8, in <module>
    import librosa; print("librosa", librosa.__version__)
AttributeError: module 'librosa' has no attribute '__version__'
```

**Comment by dpwe** [comment]
It looks like a problem with scipy.ndimage. What happens if you just type:

>>> import scipy.ndimage

?

  DAn.

**Comment by ZairMahmood** [comment]
It gave a similar error as the one described under 'Error' in my original post. After fixing scipy and rerunning the command 'import scipy.ndimage', I received no errors. Running the code from my original post still produces the same error though.

**Comment by bmcfee** [comment]
@ZairMahmood please report the output from the version listing code.

**Comment by bmcfee** [comment]
@ZairMahmood how did you install librosa, and what is your python environment?

**Comment by ZairMahmood** [comment]
Installed via pip as mentioned in the original post and I'm using the IDLE provided by Python. It looks like other Librosa code is working now after fixing scipy but the code provided to check versions is still giving the same error. Since Lib is working now, you can close this or we can try to figure out why the version attribute isn't working

**Comment by bmcfee** [comment]
Sorry, I missed that in the original post.  When you say "provided by python", what python distribution are you using?

If the `__version__` attribute is not accessible, then something is still wrong, and I'd like to get to the bottom of it before closing this out.

**Comment by dpwe** [comment]
From the original message:

File "D:\Windows\Desktop\librosa.py", line 8, in <module>
    import librosa; print("librosa", librosa.__version__)

It looks to me like you have a file called librosa.py on your Desktop,
perhaps it's the commands you're running to test out librosa.  It's
quite possible (in my python 2.7 mind, at least) that that file is
being "imported" instead of the actual installed version.  If you have
created a file called librosa.py, try renaming or deleting it.  Then I
think librosa.__version__ will become accessible.

  DAn.

**Comment by ZairMahmood** [comment]
Yup that was the error. That was pretty foolish of me to name a file like that.
Thanks again for figuring out Scipy was the issue. I wouldn't have been able to figure that out.

**Comment by dpwe** [comment]
Glad to help!  I guess this is the kind of thing behind pep-328
<https://www.python.org/dev/peps/pep-0328/>.

  DAn.
