### ISSUE TITLE
find_files does not dedupe on windows

### ISSUE THREAD

**Issue by bmcfee** [librosa/librosa#678]
#### Description
Setting up windows CI testing #677 seems to have exposed a platform-dependent bug in `find_files`, where the same file name can appear multiple times in the results.

#### Steps/Code to Reproduce

Here's a trace from a recent build:

```
[00:19:16] ======================================================================
[00:19:16] FAIL: test_util.test_files('.', None, True, False, None, 1)
[00:19:16] ----------------------------------------------------------------------
[00:19:16] Traceback (most recent call last):
[00:19:16]   File "C:\Miniconda\envs\test-environment\lib\site-packages\nose\case.py", line 197, in runTest
[00:19:16]     self.test(*self.arg)
[00:19:16]   File "C:\projects\librosa\tests\test_util.py", line 607, in __test
[00:19:16]     assert set(files) == set(output[s1][s2]), (files, output[s1][s2])
[00:19:16] AssertionError: (['C:\\projects\\librosa\\tests\\data\\test1_22050.wav', 'C:\\projects\\librosa\\tests\\data\\test1_44100.wav', 'C:\\projects\\librosa\\tests\\data\\test1_44100.wav', 'C:\\projects\\librosa\\tests\\data\\test2_8000.wav', 'C:\\projects\\librosa\\tests\\data\\test2_8000.wav'], ['C:\\projects\\librosa\\tests\\data\\test1_44100.wav', 'C:\\projects\\librosa\\tests\\data\\test2_8000.wav'])
```
The message following the assertion error indicates that the same file appears multiple times in the result of `find_files`.  This in turn causes the behavior of `offset=` and `limit=` parameters to change, and the tests fail.

#### Expected Results
A file should not appear more than once in the results list.

#### Actual Results
The file does appear multiple times.

#### Versions

Test environment is windows, librosa 0.6.0, python 2.7, 3.5, 3.6.

**Comment by bmcfee** [comment]
Follow-up: the reason that this happens is that windows, being case-insensitive, will match the same file on multiple extensions.  For example, `file.wav` will match on `ext='wav'` and `ext='WAV'`.  The `find_files` logic iterates over the extension list and concatenates the results without deduping.

On other platforms, this does not happen, because `file.wav` and `file.WAV` are treated as distinct filenames.
