### ISSUE TITLE
librosa sets multiprocessing start_method

### ISSUE THREAD

**Issue by SsnL** [librosa/librosa#747]
#### Description
After `import librosa`, `multiprocessing`'s `start_method` is set and users can't change it via `multiprocessing.set_start_method` anymore.

#### Steps/Code to Reproduce
```py
➜  test git:(stft_fft) ✗ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing as mp
>>> mp.set_start_method('spawn')
➜  test git:(stft_fft) ✗ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
^[[Aimport multiprocessing as mp
>>> mp.set_start_method('spawn')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssnl/miniconda3/lib/python3.6/multiprocessing/context.py", line 242, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

#### Expected Results
`librosa` doesn't set `multiprocessing`'s `start_method`.

#### Actual Results
`librosa` sets `multiprocessing`'s `start_method`.

#### Versions
```py
>>> import platform; print(platform.platform())
Linux-4.6.7-73_fbk21_3608_gb5941a6-x86_64-with-centos-7.5.1804-Core
>>> import sys; print("Python", sys.version)
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.1.0
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.1
```

**Comment by SsnL** [comment]
@bmcfee both `joblib` and `sklearn` sets it actually. :O. I guess it's just better to use `ctx = mp.Context('spawn')`.

**Comment by bmcfee** [comment]
Oof, thanks for looking into it!  I guess the recommended solution is to set the context before importing?

**Comment by BDHU** [comment]
+1
After importing librosa, can't change processing start method anymore.

**Comment by bmcfee** [comment]
The comments above still apply: this issue is upstream of librosa and there's nothing we can do.

**Comment by BDHU** [comment]
It seems the adding following code before importing librosa fixes the issue:

```python
if __name__ == '__main__':
    # This is necessary to bypass librosa limitation
    import torch.multiprocessing as mp
    mp.set_start_method("forkserver")

    import joblib
    import sklearn
```
