### ISSUE TITLE
module 'scipy' has no attribute 'fftpack'

### ISSUE THREAD

**Issue by giwl21** [librosa/librosa#835]
```
import librosa
Traceback (most recent call last):

  File "<ipython-input-22-989066361697>", line 1, in <module>
    import librosa

  File "C:\Users\Luqman\Anaconda2\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core

  File "C:\Users\Luqman\Anaconda2\lib\site-packages\librosa\core\__init__.py", line 110, in <module>
    from .audio import *  # pylint: disable=wildcard-import

  File "C:\Users\Luqman\Anaconda2\lib\site-packages\librosa\core\audio.py", line 11, in <module>
    import scipy.fftpack as fft

AttributeError: module 'scipy' has no attribute 'fftpack'
```

I;m not sure how to fix it, it seems that Librosa may just be outdated.  My scipy library is 1.2.1.  How can I fix this?

**Comment by bmcfee** [comment]
Please fill out the issue form template, including the details of your environment and dependency versions.  Your issue will be impossible to diagnose without that information.
