### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv' while deploying on Heroku

### ISSUE THREAD

**Issue by oleksandrkim** [librosa/librosa#887]
#### Description
Can't run librosa code while deploying my model on the web with heroku. It works fine on localhost though. The code fails at loading the sound file, resulting in No such file or directory: 'avconv': 'avconv' error. 

The code is huge and hard to understand, but the part that is failing is a simple load:
y, sr = librosa.load(file, sr=sr)

The outcome is: 

2019-05-23T03:04:19.838828+00:00 app[web.1]: Preproccesd file: 01.wav
2019-05-23T03:04:20.268864+00:00 heroku[router]: at=info method=GET path="/read_file?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cGxvYWRfdG9rZW4iOiJTb25nX29mX3RoZV9hbmNpZW50c190ZXN0X3BhcnRfMDEud2F2IiwiZXhwIjoxNTU4NTgxMjU4LjcwODQ0NDZ9.3lokBRGepYn780loh2VgkFZzVYTlwRpQ0WaQImEOYBU" host=trial-num3.herokuapp.com request_id=e5c396f4-c999-4904-96cc-5bcdab64745e fwd="99.224.55.24" dyno=web.1 connect=2ms service=1352ms status=500 bytes=892 protocol=https
2019-05-23T03:04:20.137332+00:00 app[web.1]: [2019-05-23 03:04:20,125] ERROR in app: Exception on /read_file [GET]
2019-05-23T03:04:20.137351+00:00 app[web.1]: Traceback (most recent call last):
2019-05-23T03:04:20.137353+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
2019-05-23T03:04:20.137355+00:00 app[web.1]: response = self.full_dispatch_request()
2019-05-23T03:04:20.137357+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
2019-05-23T03:04:20.137358+00:00 app[web.1]: rv = self.handle_user_exception(e)
2019-05-23T03:04:20.137360+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
2019-05-23T03:04:20.137362+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2019-05-23T03:04:20.137363+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
2019-05-23T03:04:20.137365+00:00 app[web.1]: raise value
2019-05-23T03:04:20.137367+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
2019-05-23T03:04:20.137368+00:00 app[web.1]: rv = self.dispatch_request()
2019-05-23T03:04:20.137370+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
2019-05-23T03:04:20.137372+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2019-05-23T03:04:20.137374+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_login/utils.py", line 228, in decorated_view
2019-05-23T03:04:20.137375+00:00 app[web.1]: return func(*args, **kwargs)
2019-05-23T03:04:20.137377+00:00 app[web.1]: File "/app/app/routes.py", line 251, in read_uploaded_file
2019-05-23T03:04:20.137379+00:00 app[web.1]: df_fin_UN, notes_starts = ann_data_preproc_unknown (files_un, feat_num, nt, steps, stdev, min_perc, sr, show_details, n_mels, n_fft, steps_t, dir_c=-1)
2019-05-23T03:04:20.137380+00:00 app[web.1]: File "/app/app/NeuralNetworks_funct.py", line 381, in ann_data_preproc_unknown
2019-05-23T03:04:20.137382+00:00 app[web.1]: df, y = train_data_conversion(file, nt, steps, stdev, min_perc, sr, show_details)
2019-05-23T03:04:20.137384+00:00 app[web.1]: File "/app/sound_preprocessing.py", line 18, in train_data_conversion
2019-05-23T03:04:20.137385+00:00 app[web.1]: y, sr = librosa.load(file, sr=sr)
2019-05-23T03:04:20.137387+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/librosa/core/audio.py", line 119, in load
2019-05-23T03:04:20.137389+00:00 app[web.1]: with audioread.audio_open(os.path.realpath(path)) as input_file:
2019-05-23T03:04:20.137390+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/audioread/__init__.py", line 107, in audio_open
2019-05-23T03:04:20.137392+00:00 app[web.1]: backends = available_backends()
2019-05-23T03:04:20.137394+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/audioread/__init__.py", line 86, in available_backends
2019-05-23T03:04:20.137395+00:00 app[web.1]: if ffdec.available():
2019-05-23T03:04:20.137397+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/audioread/ffdec.py", line 108, in available
2019-05-23T03:04:20.137399+00:00 app[web.1]: creationflags=PROC_FLAGS,
2019-05-23T03:04:20.137400+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/audioread/ffdec.py", line 94, in popen_multiple
2019-05-23T03:04:20.137402+00:00 app[web.1]: return subprocess.Popen(cmd, *args, **kwargs)
2019-05-23T03:04:20.137403+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/subprocess.py", line 709, in __init__
2019-05-23T03:04:20.137405+00:00 app[web.1]: restore_signals, start_new_session)
2019-05-23T03:04:20.137406+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/subprocess.py", line 1344, in _execute_child
2019-05-23T03:04:20.137408+00:00 app[web.1]: raise child_exception_type(errno_num, err_msg, err_filename)
2019-05-23T03:04:20.137415+00:00 app[web.1]: FileNotFoundError: [Errno 2] No such file or directory: 'avconv': 'avconv'

I can open github repository if you want to try to upload model by yourself.
###### Versions
alembic==0.9.6
Babel==2.5.1
blinker==1.4
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
dominate==2.3.1
elasticsearch==6.1.1
Flask==1.0.2
Flask-Babel==0.11.2
Flask-Bootstrap==3.3.7.1
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==2.1.1
Flask-Moment==0.5.2
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
guess_language-spirit==0.5.3
idna==2.6
itsdangerous==0.24
Jinja2==2.10
Mako==1.0.7
MarkupSafe==1.0
PyJWT==1.5.3
python-dateutil==2.6.1
python-dotenv==0.7.1
python-editor==1.0.3
pytz==2017.2
requests==2.18.4
SQLAlchemy==1.1.14
urllib3==1.22
visitor==0.1.3
Werkzeug==0.14.1
WTForms==2.1

psycopg2==2.7.3.1
gunicorn==19.7.1

librosa==0.6.3
tensorflow==1.12.0
pandas==0.24.2
numpy==1.16.2
Keras==2.2.4
matplotlib==3.1.0
music21==5.5.0
audioread==2.1.7
Avpy==0.1.3
ffmpeg-python==0.1.17
ffmpy==0.2.2
joblib==0.13.2
numba==0.43.1
scipy==1.3.0
scikit-learn==0.21.1
decorator==4.4.0
six==1.12.0
resampy==0.2.1

Python version 3.6.7
Do you have any suggestions? Thank you!

**Comment by bmcfee** [comment]
Please see the comments in #886.

**Comment by oleksandrkim** [comment]
> Please see the comments in #886.

Thanks a lot! I was struggling for so long.
I changed the version of audioread to a previous one and it worked. The new version was released a week ago and it causes this issue I suppose.

**Comment by Jasparr77** [comment]
Hey @oleksandrkim , how do you process your audio data in Heroku? I’m running into issues with a project and curious to see a design that works. Thanks!

**Comment by oleksandrkim** [comment]
> Hey @oleksandrkim , how do you process your audio data in Heroku? I’m running into issues with a project and curious to see a design that works. Thanks!

Can you provide some details of what is wrong with your code? I used librosa to convert sound to MEL-spectograms and it worked fine

**Comment by Jasparr77** [comment]
Sure! I’m downloading 30s Spotify samples to my static folder, then trying
to process the mp3 file with librosa. It works fine running locally, but I
can't seem to find the files when it's running on Heroku. Happy to take it
off-line from this issue (Hi, Brian!) if you want - it's lines 221:231 in
this file: https://github.com/Jasparr77/songshape_app/blob/master/routes.py

Do you have a repo I can check out and compare against?

Thanks!
Jasper

------------------------------
*From:* Oleksandr Kim <notifications@github.com>
*Sent:* Tuesday, December 17, 2019 7:46 AM
*To:* librosa/librosa
*Cc:* Jasparr77; Comment
*Subject:* Re: [librosa/librosa] FileNotFoundError: [Errno 2] No such file
or directory: 'avconv': 'avconv' while deploying on Heroku (#887)


Hey @oleksandrkim <https://github.com/oleksandrkim> , how do you process
your audio data in Heroku? I’m running into issues with a project and
curious to see a design that works. Thanks!

Can you provide some details of what is wrong with your code? I used
librosa to convert sound to MEL-spectograms and it worked fine

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/librosa/librosa/issues/887?email_source=notifications&email_token=ADTR352J2Q6O5WSF3G6OSXDQZDX6VA5CNFSM4HOZTYTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHCZ4AY#issuecomment-566599171>,
or unsubscribe
