### ISSUE TITLE
Invalid shape for monophonic audio: ndim=2, shape=(20, 345) whether I set mono=False or True when loading file

### ISSUE THREAD

**Issue by ZER-0-NE** [librosa/librosa#889]
#### Description
```librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(20, 345)```
I am trying to compute PCEN images for the given audio files. In the process, I am set mono = False so that it allows only monophonic signals as input. But it seems the statement 
```
print(f"Valid audio {librosa.util.valid_audio(data, mono=True)}")
```
produces true for both whether I set mono = True or False. Why is it so? And if it's mono, why is ndim = 2 ?
#### Steps/Code to Reproduce
```python
#Imports

import os
import wave
import glob
import csv
import matplotlib.pyplot as plt
import pandas as pd
import pylab
import librosa
import librosa.display
import numpy as np

from scipy.io import wavfile
import scipy
from skimage.restoration import (denoise_wavelet, estimate_sigma)
import argparse


def padding(data, sampling_rate, input_length):
	'''Padding of samples to make them of same length'''
	if len(data) > input_length:
		max_offset = len(data) - input_length
		offset = np.random.randint(max_offset)
		data = data[offset:(input_length+offset)]
	else:
		if input_length > len(data):
			max_offset = input_length - len(data)
			offset = np.random.randint(max_offset)
		else:
			offset = 0
		data = np.pad(data, (offset, input_length - len(data) - offset), "constant")
	return data

def audio_norm(data):
	'''Normalization of audio'''
	max_data = np.max(data)
	min_data = np.min(data)
	data = (data - min_data)/(max_data - min_data + 1e-6)
	return data - 0.5

def mfcc(data, sampling_rate, n_mfcc):
	'''Compute mel-scaled feature using librosa'''
	data = librosa.feature.mfcc(data, sr=sampling_rate, n_mfcc=n_mfcc)
	data = np.expand_dims(data, axis=-1)
	return data
	
def pcen(data, sampling_rate):
	'''Compute Per-Channel Energy Normalization (PCEN)'''
	S = librosa.feature.melspectrogram(data, sr=sampling_rate, power=1) # Compute mel-scaled spectrogram
	log_S = librosa.amplitude_to_db(S, ref=np.max) #Convert an amplitude spectrogram to dB-scaled spectrogram
	pcen_S = librosa.core.pcen(S)
	return pcen_S

def waveletDenoising(data):
	'''
	Wavelet Denoising using scikit-image
	'''
	sigma_est = estimate_sigma(pcen_S, multichannel=True, average_sigmas=True)
	im_bayes = denoise_wavelet(pcen_S, multichannel=False, convert2ycbcr=True, method='BayesShrink',
									mode='soft')
	im_visushrink = denoise_wavelet(pcen_S, multichannel=False, convert2ycbcr=True, method='VisuShrink',
									mode='soft')
	return im_bayes

def plot_and_save(data):
	fig, ax = plt.subplots(figsize=(14, 8))
	ax.imshow(im_bayes)
	# ax.set_axis_off()
	ax.get_xaxis().set_visible(False)
	ax.get_yaxis().set_visible(False)
	# pylab.savefig('spec_wavelet.jpg', bbox_inches='tight', pad_inches=0)
	plt.savefig('spec_wavelet1.jpg', dpi=500,  bbox_inches="tight", quality=95, pad_inches=0.0)

	fig.tight_layout()


def main(args):
	sampling_rate = args.resampling
	audio_duration = args.dur
	use_mfcc = args.mfcc
	n_mfcc = args.nmfcc
	file_path = args.classpath

	audio_length = sampling_rate * audio_duration
	preprocessing_fn = lambda x: x
	input_length = audio_length

	# Load files
	os.chdir(file_path)
	print("Starting to load data files")
	print("All files will be resampled to {}Hz with audio duration {}s".format(sampling_rate, audio_duration))
	for file in glob.glob("*.wav"):
		print(f"files are {file}")
		data, sr = librosa.core.load(file, sr=sampling_rate, res_type='kaiser_fast', mono=False)

		print(f"Valid audio {librosa.util.valid_audio(data, mono=True)}")
		print(data.shape)
		# apply padding
		padded_data = padding(data, sr, input_length)

		if use_mfcc:
			data = mfcc(padded_data, sampling_rate, n_mfcc)
		# else:
		# 	data = preprocessing_fn(padded_data)[:, np.newaxis]
		pcen_S = pcen(data, sr)
		denoised_data = waveletDenoising(pcen_S)
		plot_and_save(denoised_data)

if __name__ == '__main__':
	
	parser = argparse.ArgumentParser(description="Pre-Process the audio files and save as spectrogram images")
	parser.add_argument('-c', '--classpath', type=str, help='directory with list of classes', required=True)
	parser.add_argument('-s', '--resampling', type=int, default=44100, help='choose sampling rate')
	parser.add_argument('-d', "--dur", type=int, default=4, help='Max duration (in seconds) of each clip')
	parser.add_argument('-m', "--mfcc", type=bool, default=True, help='apply mfcc')
	parser.add_argument('-n', "--nmfcc", type=int, default=20, help='Number of mfcc to return')

	args = parser.parse_args()

	main(args)

```
#### Expected Results

I'm curious as to why mono=True or False leads to same True in both cases?
I'm expecting ndim=1 and no Parameter Error.

#### Actual Results
```
[Starting to load data files
All files will be resampled to 44100Hz with audio duration 4s
files are 17.wav
Valid audio True
(57437,)
Traceback (most recent call last):
  File "preprocessing.py", line 168, in <module>
    main(args)
  File "preprocessing.py", line 148, in main
    pcen_S = pcen(data, sr)
  File "preprocessing.py", line 69, in pcen
    S = librosa.feature.melspectrogram(data, sr=sampling_rate, power=1) # Compute mel-scaled spectrogram
  File "/home/abhishek/anaconda3/envs/conda/lib/python3.6/site-packages/librosa/feature/spectral.py", line 1491, in melspectrogram
    power=power)
  File "/home/abhishek/anaconda3/envs/conda/lib/python3.6/site-packages/librosa/core/spectrum.py", line 1531, in _spectrogram
    S = np.abs(stft(y, n_fft=n_fft, hop_length=hop_length))**power
  File "/home/abhishek/anaconda3/envs/conda/lib/python3.6/site-packages/librosa/core/spectrum.py", line 160, in stft
    util.valid_audio(y)
  File "/home/abhishek/anaconda3/envs/conda/lib/python3.6/site-packages/librosa/util/utils.py", line 163, in valid_audio
    'ndim={:d}, shape={}'.format(y.ndim, y.shape))
librosa.util.exceptions.ParameterError: Invalid shape for monophonic audio: ndim=2, shape=(20, 345)
```

#### Versions

Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:43:46) 
[GCC 7.3.0]
NumPy 1.14.3
SciPy 1.1.0
librosa 0.6.1

**Comment by bmcfee** [comment]
The problem here is that when `use_mfcc=True`, you're overwriting `data` (audio buffer) with MFCC's.  Then, when you call your own `pcen` function, it assumes that `data` is still audio and feeds it into melspectrogram.

I suggest two things: 1) use more descriptive variable names, 2) don't use the same variable name to represent two different types of object.  Those suggestions will make it much easier to diagnose this kind of thing going forward.
