### ISSUE TITLE
about  librosa.load error

### ISSUE THREAD

**Issue by sunnnnnnnny** [librosa/librosa#928]
Traceback (most recent call last):
2491   File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in      worker
2492     result = (True, func(*args, **kwds))
2493   File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 83, in      preprocess_speaker
2494     wavs, texts = split_on_silences(wav_fpath, words, end_times, hparams)
2495   File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 98, in      split_on_silences
2496     wav, _ = librosa.load(wav_fpath, hparams.sample_rate)
2497   File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/librosa/core/audio.py", l     ine 133, in load
2498     for frame in input_file:
2499   File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/audioread/ffdec.py", line      181, in read_data
2500     ''.join(self.stderr_reader.queue.queue)
2501 audioread.ffdec.ReadTimeoutError: ffmpeg output:

Can you give me some suggestions?

**Comment by bmcfee** [comment]
Please fill out the issue template completely, including version numbers for dependencies. Without that, we can't diagnose your problem.

**Comment by sunnnnnnnny** [comment]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/audioread/ffdec.py", line 167, in read_data
    data = self.stdout_reader.queue.get(timeout=timeout)
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 83, in preprocess_speaker
    wavs, texts = split_on_silences(wav_fpath, words, end_times, hparams)
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 98, in split_on_silences
    wav, _ = librosa.load(wav_fpath, hparams.sample_rate)
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/librosa/core/audio.py", line 133, in load
    for frame in input_file:
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/audioread/ffdec.py", line 181, in read_data
    ''.join(self.stderr_reader.queue.queue)
audioread.ffdec.ReadTimeoutError: ffmpeg output: 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "synthesizer_preprocess_audio.py", line 41, in <module>
    preprocess_librispeech(**vars(args))    
  File "/mnt/lustre/aifs/home/yqz05/Real-Time-Voice-Cloning/synthesizer/preprocess.py", line 38, in preprocess_librispeech
    for speaker_metadata in tqdm(job, "LibriSpeech", len(speaker_dirs), unit="speakers"):
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/site-packages/tqdm-4.7.2-py3.6.egg/tqdm/_tqdm.py", line 594, in __iter__
  File "/mnt/lustre/aifs/home/yqz05/miniconda3/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
audioread.ffdec.ReadTimeoutError: ffmpeg output:


environments is:
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux

multiprocess           0.70.8
librosa                0.6.3
audioread              2.1.6
numpy                  1.16.4


I don't know if this information is enough, I hope to get your reply.

**Comment by bmcfee** [comment]
> audioread.ffdec.ReadTimeoutError: ffmpeg output:

The problem here is that ffmpeg is stalling out for some reason.  Are you able to load the file in question with another application?  What format is it in?

It's possible that there's some bad interaction happening between multiprocessing and audioread, though these things usually play well together in my experience.

If the file in question is not mp3 format (and can be loaded by libsndfile), you may want to try upgrading to the latest librosa (0.7) which changes out the decoder library.

At any rate, I don't think this is a problem with librosa, but rather something broken upstream in the decoder or the multiprocessing environment.
